### ISSUE TITLE
Short arguments?

### ISSUE THREAD

**Issue by Ultra980** [TheR1D/shell_gpt#1]
Hello, is there a plan to implement short arguments (such as `-s` instead of `--shell` and `-e` instead of `--execute`)? Also, if they are implemented, will they be combined (like `-se` instead of `-s -e`)? I think this would enhance the experience.

**Comment by TheR1D** [comment]
Will be implemented in PR https://github.com/TheR1D/shell_gpt/pull/2

**Comment by TheR1D** [comment]
Implemented in https://github.com/TheR1D/shell_gpt/pull/2
