### ISSUE TITLE
[Improvement] Add an option to send the OS information

### ISSUE THREAD

**Issue by Ultra980** [TheR1D/shell_gpt#10]
Hello, thanks for this awesome project!
I wanted to make something similar some time ago, but never got the time. The idea also involved sending some system information to chatGPT in the prompt. Since this project already exists, I made [a pull request](https://github.com/TheR1D/shell_gpt/pull/9) to add this functionality. This adds the `--send-os-info` (or `-o`) flag, that adds the OS, release, and Linux Distro (if applicable). It's especially useful for OS-specific things, such as package management or editing configs.
Once again, thanks for this project!

**Comment by TheR1D** [comment]
Hello, thank you for PR and feedback. I think the feature you are suggesting can be done using some shell magic: `sgpt -se "update my system $(lsb_release -d)` (`lsb_release` might not be included in your distro by default). Also note that all GPT-3 models are trained on one year old data, and passing specific up to date version of distro will not make sense to the models, they might not know them yet. I think just to include the os name manually in your prompt is also acceptable in this case 🙂`sgpt -se "update my Ubuntu os"

**Comment by Ultra980** [comment]
Well, it will probably ignore the kernel version, but it's useful for non-linux OSes. Also, instead of telling it which distro it uses every time, isn't it easier to just add a flag to the command?

**Comment by TheR1D** [comment]
I believe most shell users are very familiar how to update the system without extra tool. In my opinion for this use case it would be enough to have some alias which will do same thing without calling external source:
```
alias update="apt update && apt upgrade"
update
```
Or if you really want to do it with sgpt, I would suggest to use power of open source and fork it for your specific use case 🙂.
Closing the issue for now, with possibility to reopen it in the future, if we will have simmilar feature requests.

**Comment by Ultra980** [comment]
What about newbies?

I'll do what you said, and fork it. Perhaps I'll generally make it more suitable for managing a system :)

**Comment by TheR1D** [comment]
This feature will be implemented as part of prompt engineering PR https://github.com/TheR1D/shell_gpt/pull/70
Reopening the issue, as I was mentioning it above :)
