### ISSUE TITLE
Use an example in the prompt, to encourage ChatGPT to behave

### ISSUE THREAD

**Issue by joeytwiddle** [TheR1D/shell_gpt#101]
Sometimes ChatGPT is disobedient. For example: #99 But I don't know how common this is. Do you see this often? (I think I might have seen it once.)

Due to GPT's predictive nature, it was recommended to prompt it with an incomplete conversation, so that it would complete the rest. Although ChatGPT is different, it may respond to the same treatment.

This approach (shown below) is taken by [`plz`](https://github.com/zahidkhawaja/rusty/blob/c74a7439c40153e5f0f60120ae7f5d5d4d18fbe9/src/main.rs#L42-L63), while [`rusty`](https://github.com/m1guelpf/plz-cli/blob/9d4549ba972a3b0d03533dced6539c6f45b3d5fd/src/main.rs#L147) passes `#!/bin/bash\n` to initialise the response.

### Suggestion

When we are asking ChatGPT to generate some shell code, we may want to give it an example first.

```
{The current shell prompt rules}

Input: List the files in the root folder
Output: ls /

Input: ${user_question_here}
Output: 
```

For the code prompt, even though we don't know the user's target language, it might still be possible to do something similar.

**Comment by joeytwiddle** [comment]
I have put a solid proposal in #102, to better share the idea. Feel free to close it.

**Comment by TheR1D** [comment]
Prompts improvements were inmplemented in https://github.com/TheR1D/shell_gpt/pull/107 now `sgpt` performs better when making suggestions for `--code` or `--shell`
