### ISSUE TITLE
Add streaming support for better UX.

### ISSUE THREAD

**Issue by lpurdy01** [TheR1D/shell_gpt#105]
The application would feel much more responsive if it supported the API's streaming token interface. This would dramatically improve responsiveness.

@parsapoorsh has an example of this on their fork with commit:
https://github.com/parsapoorsh/shell_gpt/commit/1d6cad0e60da181d599be09dfb973be3c1d1d592

It would be really helpful if that or something like it could be rebased to main and opened as a pull request.

**Comment by TheR1D** [comment]
Yes, I didn't notice there is cool streaming stuff in his PR, my bad.
