### ISSUE TITLE
SSL Errors Using Requests Library Behind Corporate Firewall

### ISSUE THREAD

**Issue by jacobtaunton** [TheR1D/shell_gpt#112]
If you are getting SSL errors when trying to access a corporate firewall with python requests, you may need to change the CA bundle that requests uses. By default, requests uses its own embedded bundle of certificates, which may not match the ones used by your firewall. To fix this, you can set the REQUESTS_CA_BUNDLE environment variable to point to a file that contains the system CA certificates. For example, on Linux you can do:

export REQUESTS_CA_BUNDLE=$HOME/cert.pem

This will tell requests to use the cert.pem file in your home directory as the CA bundle. You can also use the verify argument in requests to specify a different CA bundle for each request. For more details, see https://stackoverflow.com/a/33717517/1695680. I hope this helps you solve your issue. Cheers!

**Comment by jacobtaunton** [comment]
This fixes the issue with request library but then there is another problem with Pip no longer working with same ssl error. Then you would have to do this each time if you would like to use pip.
pip install <package_name> --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org

**Comment by lindblb** [comment]
> You can also use the verify argument in requests to specify a different CA bundle for each request.

How do you do that within the shell_gpt shell though? @jacobtaunton
