### ISSUE TITLE
TOML project configuration

### ISSUE THREAD

**Issue by TheR1D** [TheR1D/shell_gpt#117]
Migrate to [TOML](https://toml.io/en/) configuration. It should include multiple "bundles" of dependecies for normal, dev, and testing environments. Move configurations of `black` and `pytest` to the toml file. Also migrate `pre-push.sh` to TOML config file using [pre-commit](https://pre-commit.com/). Configurate CI/CD (GitHub Actions) pipelines with the new TOML.

**Comment by slangenbach** [comment]
I am willing to work on this issue.  
Would you also want to move from setup.py to poetry?  
IMHO this would make package handling, building and publishing more convenient.

**Comment by TheR1D** [comment]
Sure, the idea is to move what possible to toml, including `setup.py`, and we can migrate to **poetry** to manage dependencies. Additionaly we could have some sort of "quick start" guide with the description how to isntall/manage dependencies, would be usefull for contributers.
