### ISSUE TITLE
OPENAI_ORGANIZATION seems to be needed now

### ISSUE THREAD

**Issue by Remowylliams** [TheR1D/shell_gpt#126]
Hello,
  I'm not sure if it was due to my setting up payment for the openai API service or if some change has happened.
I updated my sgpt which has been working great till this latest upgrade I think I'd been using 0.7.1 now 0.8.1

After upgrading I had to add a key. (as stated, previously I was working fine.) So I added a new key and got the 401 unauthorized message.

I tried clearing the .config folders and tried again with a new key and still failed 401.
After puzzling and looking at the sgptrc file. I plunked in:
`OPENAI_ORGANIZATION=<my organization identifier>`

I also wrote my `OPENAI_API_KEY=<ley>` where it had originally said AR 
And from that point on everything worked lovely. 

I'm guessing all that was missing was the OPENAI_ORGANIZATION= piece and things would have worked fine as the shel-gpt\api_key.txt did get created 

Any info clarifying this would be greatly appreciated.

Thanks for making shell-gpt it's been great fun.

**Comment by TheR1D** [comment]
There is new path for config file in `~/.config/shell_gpt/.sgptrc`
