### ISSUE TITLE
Usage without quotes?

### ISSUE THREAD

**Issue by Durafen** [TheR1D/shell_gpt#128]
Hello,
Thank you for your time and for maintaining this useful project!

Is it possible to execute the prompt without having to add quote characters (" ") around the input text?

**Comment by xsoc** [comment]
I got around it by adding a function to my `.bashprofile` (well, actually `.zprofile`)
```
function ai () {
    sgpt "$*"
}
```
Then you can just type `ai How do I cook toast`

**Comment by Durafen** [comment]
I also added aic function to start a fast repl session.

```
function aic () {
    export LC_ALL=C
    local chat_id=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)
    if [[ "${1:0:1}" == "-" || "${1:0:1}" == "?^?^?" ]]; then
        sgpt --repl $chat_id $1 "${*:2}"
    else
        sgpt --repl $chat_id "$*"
    fi
    echo "Chat ID: $chat_id"

}
```

**Comment by xsoc** [comment]
@Durafen, dumb question, what's LC_ALL being used for?

**Comment by Durafen** [comment]
> @Durafen, dumb question, what's LC_ALL being used for?

Without it, the string generation was throwing an encoding related error, so the locale was set to ASCII. 
GPT4 suggested this as one of the solutions, I bet there might be better alternatives.

**Comment by transcendr** [comment]
@xsoc Our AI overlords say:

`LC_ALL` is an environment variable that overrides all other locale settings (i.e. `LANG` and `LC_*`) ¹. It is used to temporarily run a specific program under a different locale ¹. In this case, `LC_ALL=C` sets the locale to the C locale, which is a special locale that is meant to be the simplest locale ². This can improve performance significantly because parsing UTF-8 data has a cost ².

(1) Environment variable LC_ALL is always unset by default. why LC_ALL is .... https://superuser.com/questions/842591/environment-variable-lc-all-is-always-unset-by-default-why-lc-all-is-unset Accessed 06/04/2023.
(2) What does "LC_ALL=C" do? - Unix & Linux Stack Exchange. https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do Accessed 06/04/2023.
(3) setlocale() — Set Locale - IBM. https://www.ibm.com/docs/api/v1/content/ssw_ibm_i_74/rtref/setloc.htm Accessed 06/04/2023.

**Comment by drpedapati** [comment]
> ```shell
> function ai () {
>     if [[ "${1:0:1}" == "-" || "${1:0:1}" == "—" ]]; then
>         sgpt $1 "${*:2}"
>     else
>         sgpt "$*"
>     fi
> }
> ```

These are really cool - could you post other ai functions we could add to our bashrc and update over time

**Comment by xsoc** [comment]
@drpedapati, I wrote a few others you can check out in [#53](https://github.com/TheR1D/shell_gpt/discussions/53#discussioncomment-5530512).

**Comment by payrequestio** [comment]
`ai --chat number what is my favorite number
`Usage: sgpt [OPTIONS] [PROMPT]
Try 'sgpt --help' for help.
╭─ Error   Missing string PROMPT.  

**Does anyone know how I can make --chat work?**

**Comment by xsoc** [comment]
Because the alias wraps *all params* up in the quotes, you'd either have to write a function, or just write seperate aliases for each use case, such as
'''
alias aichat="sgpt --repl temp"
'''

**Comment by endolith** [comment]
For use with Cmder in Windows, I added this line to the end of `user_aliases.cmd`: 

```
s=sgpt --shell "$*"
```

Now I can type commands in English by prepending `s`:
```
λ s remove conda environment autogpt
conda remove --name autogpt --all -y
Execute shell command? [y/N]: y
```

**Comment by TheR1D** [comment]
I believe this issue is solved by using some aliases and extra shell magic.

**Comment by galchinsky** [comment]
Here are a possible patch and a workaround:

The patch is to use List[str] as the type of the prompt parameter and then join it to form a string. Works for me, not sure if it breaks anything for others

```
#sgpt/app.py
from typing import List

def main(
    prompt: List[str] = typer.Argument(
        None,
        show_default=False,
        help="The prompt to generate completions for.",
    )
# .....
    install_integration: bool = typer.Option(
        False,
        help="Install shell integration (ZSH and Bash only)",
        callback=install_shell_integration,
        hidden=True,  # Hiding since should be used only once.
    ),
) -> None:
    prompt = " ".join(prompt)
```

Demo:

```
$ sgpt hello
Hello! How can I assist you today?
$ sgpt hello bro
Hello! How can I assist you today?
$ sgpt "hello bro"
Hello! How can I assist you today?
$sgpt --code C++ function that returns 42
int return42() {
    return 42;
}
$ sgpt --chat temp remember the number 123123
Sure, I have remembered the number 123123.
$ sgpt --chat temp1 remember the number 123123
I have remembered the number 123123.
$ sgpt --chat temp1 now tell me the number
The number is 123123.
```

As a workaround (in case someone can't edit the app.py), I asked GPT4 to write a wrapper with the same idea

```
#!/usr/bin/env python
import argparse
import subprocess
import shlex
import sys

def construct_sgpt_command(args, prompt):
    # Base sgpt command
    sgpt_command = ["sgpt"]

    # Add flags based on argparse arguments
    if args.code:
        sgpt_command.append("--code")
    if args.shell:
        sgpt_command.append("--shell")
    if args.version:
        sgpt_command.append("--version")
    if args.editor:
        sgpt_command.append("--editor")
    if args.chat:
        sgpt_command.extend(["--chat", args.chat])
    if args.repl:
        sgpt_command.extend(["--repl", args.repl])
    if args.temperature is not None:
        sgpt_command.extend(["--temperature", str(args.temperature)])
    if args.top_probability is not None:
        sgpt_command.extend(["--top-probability", str(args.top_probability)])
    if args.model:
        sgpt_command.extend(["--model", args.model])
    if args.no_cache:
        sgpt_command.append("--no-cache")

    # Add prompt
    sgpt_command.append(prompt)

    return sgpt_command

def main():
    parser = argparse.ArgumentParser(description='ShellGPT Wrapper Script')

    # Define optional flags
    parser.add_argument('--code', action='store_true', help='Generate only code')
    parser.add_argument('--shell', action='store_true', help='Generate and execute shell commands')
    parser.add_argument('--version', action='store_true', help='Show version information')
    parser.add_argument('--editor', action='store_true', help='Open $EDITOR to provide a prompt')
    parser.add_argument('--chat', help='Follow conversation with id, use "temp" for quick session')
    parser.add_argument('--repl', help='Start a REPL (Read–eval–print loop) session')
    parser.add_argument('--temperature', type=float, help='Randomness of generated output')
    parser.add_argument('--top-probability', type=float, help='Limits highest probable tokens (words)')
    parser.add_argument('--model', help='Large language model to use')
    parser.add_argument('--no-cache', action='store_true', help='Do not use cached responses')

    # Define a catch-all for the remaining arguments
    parser.add_argument('prompt', nargs='*', help='The prompt to send to ShellGPT')

    # Parse the arguments
    args = parser.parse_args()

    # Concatenate all non-flag arguments into a single prompt string
    prompt = ' '.join(args.prompt)

    # Construct the ShellGPT command
    sgpt_command = construct_sgpt_command(args, prompt)

    # Execute the ShellGPT command
    subprocess.run(sgpt_command)

if __name__ == "__main__":
    main()
```
