### ISSUE TITLE
Unable to get any output. Error: HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/completions

### ISSUE THREAD

**Issue by PrabuddhMathur** [TheR1D/shell_gpt#13]
It is showing me this error even when I've created and kept the API key when asked in the program. Please help me to fix this.

**Comment by nmarks99** [comment]
I had the same issue the first time I ran `sgpt` but then I ran it again and it seemed to work fine since then

**Comment by PrabuddhMathur** [comment]
@nmarks99 I tried everything, even restarting didn't work for me. What to do? Did you do anything special for getting the API key?

**Comment by TheR1D** [comment]
It happens because of OpenAI API limitaions. You can read more about requests llimits [here](https://platform.openai.com/docs/guides/rate-limits/overview)
