### ISSUE TITLE
shell-gpt tests/*.py get installed to site-packages/tests - intentional or bug?

### ISSUE THREAD

**Issue by jhgit** [TheR1D/shell_gpt#135]
The current setup.py uses find_packages().  In the current git repo, this finds tests as a package, and so includes tests as part of the bdist.

This winds up installing tests/*.py into <prefix>/lib/pythonX.Y/site-packages/tests.  Is this intentional that it installs tests specific to shell-gpt into a generically named 'tests' directory in site-packages?

Perhaps the bdist should not include the tests/*.py files?

**Comment by jhgit** [comment]
See also discussion in a downstream packager - https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270542

Note that installing to site-packages/tests/ creates a real life conflict with another package - https://github.com/greenbone/notus-scanner

It is possible the notus-scanner package is also mistaken in installing its test files to site-packages/tests as well.

**Comment by TheR1D** [comment]
@jhgit Should be fixed in the lates release `0.8.3`. Could you please confirm it?

**Comment by jhgit** [comment]
I think using [MANIFEST.in](https://packaging.python.org/en/latest/guides/using-manifest-in/) would do the job to get tests in the sdist (and not the bdist):

    $ cat MANIFEST.in
    graft tests

**Comment by TheR1D** [comment]
@jhgit Thank you, shoud be fixed.
