### ISSUE TITLE
when used on powershell it doesn't actually use powershell

### ISSUE THREAD

**Issue by Kreijstal** [TheR1D/shell_gpt#140]
PS C:\Users\kreij\ok\shell_gpt> sgpt --shell "list all files sorted by date"
Get-ChildItem | Sort-Object LastWriteTime -Descending
Execute shell command? [y/N]: y
'Get-ChildItem' is not recognized as an internal or external command,

**Comment by quarion** [comment]
I have the same error, but the description of this issue does not seem accurate. The command is proper powershell, it just not being executed, and the above error is returned instead.

**Comment by xihuai18** [comment]
![image](https://user-images.githubusercontent.com/23721828/229721850-458cb704-a857-4721-85e0-d8f09530d457.png)
