### ISSUE TITLE
Make sgpt much better!!!

### ISSUE THREAD

**Issue by garymcintire** [TheR1D/shell_gpt#144]
Two things would make this tool much better
1. Accept the prompt from stdin. I did this by using this   prompt: str = typer.Argument(... if sys.stdin.isatty() else sys.stdin.read(), ...
3. Have an option for --gpt that stops the prefix prompt so we can use this to ask GPT any kind of question. Currently it will say I'm sorry, but as a Command Line App ShellGPT, I am not capable ...

**Comment by garymcintire** [comment]
Here are some uses for the stdin optin above
(echo 'summarize this file for me'; cat main.py) | sgpt
or
(echo 'explain these files to me'; ls /var/log) | sgpt

**Comment by garymcintire** [comment]
Another goodie would be an option for --pure-code which would print the code only but 'without' the backquotes so you can do this
sgpt --pure-code 'python code for printing first 10 prime numbers'  | python

**Comment by garymcintire** [comment]
> Two things would make this tool much better
> 
>     1. Accept the prompt from stdin. I did this by using this   prompt: str = typer.Argument(... if sys.stdin.isatty() else sys.stdin.read(), ...
> 
>     2. Have an option for 'no preprompt' so we can use this to ask GPT any kind of question. Currently it will say I'm sorry, but as a Command Line App ShellGPT, I am not capable ...

In 1, I should have shown the whole line
prompt: str = typer.Argument(... if sys.stdin.isatty() else sys.stdin.read(),  show_default=False, help="The prompt to generate completions for."),

**Comment by garymcintire** [comment]
Having said that I do love this tool :-)

**Comment by lpurdy01** [comment]
#80 #86 #93 
Good luck getting stdin added.

**Comment by lpurdy01** [comment]
oh and #35
