### ISSUE TITLE
Handle ChatGPT input limit

### ISSUE THREAD

**Issue by julianbarg** [TheR1D/shell_gpt#155]
ChatGPT 3.5 turbo seems to have an input limit for the API of 4,096 tokens. In practice I hit that limit quickly and then you receive a 400 Client Error. For example, in the example below I hit that after just one request (had to rename the file to .txt to allow github to upload, place in /tmp/shell_gpt/chat_cach without file extension to reproduce). By going into the cache and removing some of the cached messages, you can clear up the error to continue the session. A sensible way of handling this would be to truncate back messages while preserving the initial prompt I believe.

[test.txt](https://github.com/TheR1D/shell_gpt/files/11185830/test.txt)

**Comment by julianbarg** [comment]
I just realized, I vaguely remember reading somewhere ChatGPT handles this on their website by using a separate neural network to summarize the conversation so far. Python has tools like TextBox, https://github.com/RUCAIBox/TextBox , that could do something like that on a slightly more primitive scale. Assuming there is a tool there that respects word limits. To balance responsiveness and utility, workflow could be, make api call, run neural network for summary in the background, when the user runs the next api call use new summary if its ready or something truncated if its not ready yet.

**Comment by xsoc** [comment]
You'd have to implement OpenAI's [tiktoken](https://github.com/openai/tiktoken) token calculator. You can play around the the [demo version](https://platform.openai.com/tokenizer) on their site. Honestly the simplest solution is just to do what OpenAI did early on, and cull early messages as the limit approaches - ChatGPT 'forgets' the start of the conversation), worry about a more complex summarizing implementation later on.

**Comment by TheR1D** [comment]
```
sgpt --show-chat db
user: ###
...
Prompt: create postgres docker container with username=test_user, password=test_password, database=todo
###
assistant: docker run --name postgres -e POSTGRES_USER=test_user -e POSTGRES_PASSWORD=test_password -e POSTGRES_DB=todo -p 5432:5432 -d postgres:latest
user: name container as todo_db
assistant: docker run --name todo_db -e POSTGRES_USER=test_user -e POSTGRES_PASSWORD=test_password -e POSTGRES_DB=todo -p 5432:5432 -d postgres:latest
user: create a table in created container in "todo" database task: str, done: bool
assistant: docker exec -it todo_db psql -U test_user -c "CREATE TABLE todo (task TEXT, done BOOLEAN);" todo
user: insert random record to created table
assistant: docker exec -it todo_db psql -U test_user -c "INSERT INTO todo (task, done) VALUES ('Complete task 1', false);" todo
user: task = build a simple todo app
assistant: docker exec -it todo_db psql -U test_user -c "INSERT INTO todo (task, done) VALUES ('Build a simple todo app', false);" todo
user: show all records in todo table
assistant: docker exec -it todo_db psql -U test_user -c "SELECT * FROM todo;" todo

sgpt "summarize conversation: $(sgpt --show-chat db | tail +8)" | sgpt --chat extended_db "What table did we create?"
The user created a table named "todo" with columns "task" and "done".
...
```

**Comment by julianbarg** [comment]
> ```
> sgpt --show-chat db
> user: ###
> ...
> Prompt: create postgres docker container with username=test_user, password=test_password, database=todo
> ###
> assistant: docker run --name postgres -e POSTGRES_USER=test_user -e POSTGRES_PASSWORD=test_password -e POSTGRES_DB=todo -p 5432:5432 -d postgres:latest
> user: name container as todo_db
> assistant: docker run --name todo_db -e POSTGRES_USER=test_user -e POSTGRES_PASSWORD=test_password -e POSTGRES_DB=todo -p 5432:5432 -d postgres:latest
> user: create a table in created container in "todo" database task: str, done: bool
> assistant: docker exec -it todo_db psql -U test_user -c "CREATE TABLE todo (task TEXT, done BOOLEAN);" todo
> user: insert random record to created table
> assistant: docker exec -it todo_db psql -U test_user -c "INSERT INTO todo (task, done) VALUES ('Complete task 1', false);" todo
> user: task = build a simple todo app
> assistant: docker exec -it todo_db psql -U test_user -c "INSERT INTO todo (task, done) VALUES ('Build a simple todo app', false);" todo
> user: show all records in todo table
> assistant: docker exec -it todo_db psql -U test_user -c "SELECT * FROM todo;" todo
> 
> sgpt "summarize conversation: $(sgpt --show-chat db | tail +8)" | sgpt --chat extended_db "What table did we create?"
> The user created a table named "todo" with columns "task" and "done".
> ...
> ```

I was thinking about something like that, too. My intuition was that this is actually an unnecessary API call for a task that really usually is not urgent. Also, Turbo GPT3.5 is quite bad at handling length (e.g., "cut by 5%") and the summary should be as verbose as possible while fitting into the length constraint.

But! It is by far the best bang-for-the-buck option. Easy to implement. Anything more than that might be an overkill. So maybe offer that and put it behind an optional flap?

**Comment by KeithHanson** [comment]
This is a little tangential, but I did just hit this error in a repl session and it's got me thinking. 

I think anything more than truncating down to the token limit somehow for the current implementation is too much, yeah? This seems like a super straightforward implementation of a basic memory/context and that's a good thing. 

BUT, as suggested, perhaps other implementations are behind flaps/switches/configs would make sense?

Initially, I wanted to see how the memory worked in this and began diving in. But now that I've hit this error, I'm thinking I should just do it :P 

I'd like to implement a more permanent memorization and recall system by taking advantage of an embeddings database and watching for things like RECALL and MEMORIZE THIS sort of prompts. This would give you a much much larger memory that could be useful on top of the chat history. 

Is this anti-thetical to the current design, though? I'm hoping I could implement this with as minimal fuss since this is langchain based, but I'm still new to all of this ecosystem :) Interested in opinions!

But, I'd rather not overcomplicate a

**Comment by KeithHanson** [comment]
Oh! Wow. It's not langchain at all - though I don't think it'd be hard to create a langchain client and tap into all of that, while still supporting everything you've done to date.

**Comment by GiuseppeMus** [comment]
I quickly reach the limit with error 400 in step by step code development. I understand that this thread talks about this problem...is this correct? web chat does not seem to be affected by this problem because it truncates old messages in the chat (?). Is this a problem that is being worked on or is it unsolvable? Thanks for your contribution. Greetings. Giuseppe

**Comment by gimi-q** [comment]
the input limit does seem to limit the usefulness of this at present. I cant even do git diff  | sgpt.. without hitting the limit. 

if my prompt is to long for the web chatgpt version i use: https://chatgpt-prompt-splitter.jjdiaz.dev/

very manual and tedious but it is able to handle longer content without losing the context too easily. 

I understand some technical limitations mentioned above but are we not able to do something similar with shell-gpt version? 

thanks

**Comment by TheR1D** [comment]
Latest GPT-4 models allow 128,000 tokens input which is x30 than GPT-3.5. I think it should be enought to handle large text inputs discussed here. Given that I'm closing this issue, but feel free to reopen it if additional relevant information arises.
