### ISSUE TITLE
How to install it by using micromamba

### ISSUE THREAD

**Issue by hustcer** [TheR1D/shell_gpt#168]
Hi,

I'm using [mamba](https://github.com/mamba-org/mamba): https://mamba.readthedocs.io/en/latest/index.html to manage packages
```bash
micromamba install shell-gpt -n base
```
Got an error output as follows:
```console
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ shell-gpt   does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
```
Any workaround? thanks

**Comment by TheR1D** [comment]
Closing this issue due to its age and lack of similar reports/requests from other users.
