### ISSUE TITLE
Please allow asking for commands for a different shell, e.g. cmd.exe/bash on Windows

### ISSUE THREAD

**Issue by Boscop** [TheR1D/shell_gpt#186]
I'm on Win10 where I have powershell, cmd.exe and bash (sh.exe from Git) available (in addition to bash/zsh/nushell in WSL2). 
It's fine if ShellGPT assumes powershell by default, but sometimes I want to generate a command for cmd.exe or sh.exe, also sometimes I want to generate a command for running on another linux machine (like my synology NAS or raspberry PI or WSL2 or in virtualbox or on another host where `sgpt` is not installed).
It would be really nice if ShellGPT would allow custom prompt presets, so that I can make a preset for each OS/SHELL combination and then pass the preset by name with `--preset name`/`-p name`.

For now it would also be sufficient if the user could override the inferred OS/SHELL via CLI args, so the given values will be inserted in the shell prompt template. E.g. in PowerShell, I could call `sgpt --shell bash "list extensions of all files"` (in that case, it could still use the inferred value for OS, because it's not overridden with `--os`).
Could you please add this feature? :)

**Comment by xsoc** [comment]
@TheR1D won't it just use whatever shell it was called from?

**Comment by TheR1D** [comment]
Yes, ShellGPT detects the environment in which it is being executed. In Windows `cmd.exe`, it provides CMD commands, while in PowerShell, it delivers PowerShell commands accordingly. However, I believe the requested use case involves using sgpt on a Windows machine while generating commands for different operating systems or shells. This can be easily done using coming System Roles feature.
