### ISSUE TITLE
Suggestion: Add [e] option to `--shell` to explain the command to let user understand it before running

### ISSUE THREAD

**Issue by Boscop** [TheR1D/shell_gpt#187]
Suggestion: Add [e] option to `--shell` to explain the command to let user understand it before running.
E.g. instead of just
```sh
❯ sgpt -s "optimize git repo disk usage"
git gc --aggressive --prune=all
Execute shell command? [y/N]:
```
having
```sh
❯ sgpt -s "optimize git repo disk usage"
git gc --aggressive --prune=all
Execute shell command? [y/N/e=explain]:
```
if the user chooses `[e]`, it will explain the command, and print it again at the end and ask again if it should execute it.
This would let users learn what all the constituents of the command mean. (This is a simple example, but some commands are more complex so it will be useful.)

**Comment by ShykhovMyron** [comment]
Would be perfect to add same stuff to ` --repl --shell` mode but as a start its also good

**Comment by TheR1D** [comment]
Not pretty, but right a quick solution:
`"n" | sgpt -s "optimize git repo disk usage" | sgpt explain`

**Comment by Boscop** [comment]
@TheR1D The important point is that the user first has to see the command (before deciding to explain or not), so that he can check if he understands all constituents. If not, he would choose explain, and then execute if he's fine with what the command will actually do. 
This is useful if the command e.g. includes flags that you don't know, to quickly check what those flags mean before running it.
In many instances sgpt will suggest a command that you fully understand, then you'd run it right away without choosing `explain`.
