### ISSUE TITLE
The way of adding socks5 proxy  

### ISSUE THREAD

**Issue by dondonw1** [TheR1D/shell_gpt#189]
In case it is useful for somebody, socks5 proxy can be added by this way:

Edit client.py:
~/.local/lib/python3.x/site-packages/sgpt$ nano client.py

By adding below code:

import socks
import socket

# Define the proxy server URL and port number
proxy_host = '<proxy-server-url>'
proxy_port = <port>
proxy_username = '<username>'
proxy_password = '<password>'

# Set up the SOCKS5 proxy with authentication
socks.set_default_proxy(socks.SOCKS5, proxy_host, proxy_port, username=proxy_username, password=proxy_password)
socket.socket = socks.socksocket

**Comment by TheR1D** [comment]
Thanks, added this to [wiki page](https://github.com/TheR1D/shell_gpt/wiki#socks5-proxy)

**Comment by marcoleder** [comment]
How is this done in the new version?
I saw that client.py got removed with PR https://github.com/TheR1D/shell_gpt/pull/414 and the export https_proxy=socks5://ip:port does not work for me...
