### ISSUE TITLE
allowing "e" execution in REPL for non-default roles

### ISSUE THREAD

**Issue by lalligagger** [TheR1D/shell_gpt#197]
Looking at:
https://github.com/TheR1D/shell_gpt/blob/a054a900958954400004e54bc7739ba94a75de1f/sgpt/handlers/repl_handler.py#L41

And playing with newly created roles, I can see the security issues in allowing arbitrary roles to execute. Any thoughts on opening up this functionality with appropriate warnings in place? My current hack is to call my custom role "shell" while overwriting the shell.json, but I'd like to leave the default options available and not be sneaky about it.

**Comment by TheR1D** [comment]
Not sure what is the security issue in this case, user can review the output and decide what to do with the suggestion.

**Comment by lalligagger** [comment]
Ask is to add a field for `python` or `shell` execution for any custom
role, to set repl behavior. Last I tried repl execution does not work with
custom roles... have to override shell or python role.

**Comment by TheR1D** [comment]
Closing this issue due to its age and lack of similar reports/requests from other users.
