### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by oscarc231** [TheR1D/shell_gpt#199]
Any sgpt command (e.g., sgpt "mass of sun") produces a long output that ends with
`HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/chat/completions`

**Comment by sylv-io** [comment]
Same here. I have gpt+ and used the API for the first time today. So I don't think this is a rate limit issue.

**Comment by TheR1D** [comment]
Pinned issue https://github.com/TheR1D/shell_gpt/issues/201
