### ISSUE TITLE
I asked for a ascii shrug emoji as sgpt shrugged hard. 

### ISSUE THREAD

**Issue by Remowylliams** [TheR1D/shell_gpt#202]
PS C:\Users\remo> sgpt "ascii emoji for shrug"
¯\_(ツ)_/¯╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\remo\AppData\Roaming\Python\Python310\site-packages\sgpt\app.py:159 in main             │
│                                                                                                  │
│   156 │   │   │   caching=cache,                                                                 │
│   157 │   │   )                                                                                  │
│   158 │   else:                                                                                  │
│ ❱ 159 │   │   full_completion = DefaultHandler(client, role_class).handle(                       │
│   160 │   │   │   prompt,                                                                        │
│   161 │   │   │   model=model.value,                                                             │
│   162 │   │   │   temperature=temperature,                                                       │
│                                                                                                  │
│ ╭───────────────────────────────── locals ──────────────────────────────────╮                    │
│ │        api_host = 'https://api.openai.com'                                │                    │
│ │         api_key = 'some key was here'   │                    │
│ │           cache = True                                                    │                    │
│ │            chat = None                                                    │                    │
│ │          client = <sgpt.client.OpenAIClient object at 0x000001DBFF5ABB20> │                    │
│ │            code = False                                                   │                    │
│ │     create_role = None                                                    │                    │
│ │          editor = False                                                   │                    │
│ │      list_chats = None                                                    │                    │
│ │      list_roles = None                                                    │                    │
│ │           model = <ModelOptions.GPT3: 'gpt-3.5-turbo'>                    │                    │
│ │          prompt = 'ascii emoji for shrug'                                 │                    │
│ │            repl = None                                                    │                    │
│ │            role = None                                                    │                    │
│ │      role_class = <sgpt.role.SystemRole object at 0x000001DBFF5ABAF0>     │                    │
│ │           shell = False                                                   │                    │
│ │       show_chat = None                                                    │                    │
│ │       show_role = None                                                    │                    │
│ │    stdin_passed = False                                                   │                    │
│ │     temperature = 0.1                                                     │                    │
│ │ top_probability = 1.0                                                     │                    │
│ ╰───────────────────────────────────────────────────────────────────────────╯                    │
│                                                                                                  │
│ C:\Users\remo\AppData\Roaming\Python\Python310\site-packages\sgpt\handlers\handler.py:28 in      │
│ handle                                                                                           │
│                                                                                                  │
│   25 │   def handle(self, prompt: str, **kwargs: Any) -> str:                                    │
│   26 │   │   messages = self.make_messages(self.make_prompt(prompt))                             │
│   27 │   │   full_completion = ""                                                                │
│ ❱ 28 │   │   for word in self.get_completion(messages=messages, **kwargs):                       │
│   29 │   │   │   typer.secho(word, fg=self.color, bold=True, nl=False)                           │
│   30 │   │   │   full_completion += word                                                         │
│   31 │   │   typer.echo()                                                                        │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ full_completion = '¯\\_(ツ)_/¯'                                                              │ │
│ │          kwargs = {                                                                          │ │
│ │                   │   'model': 'gpt-3.5-turbo',                                              │ │
│ │                   │   'temperature': 0.1,                                                    │ │
│ │                   │   'top_probability': 1.0,                                                │ │
│ │                   │   'caching': True                                                        │ │
│ │                   }                                                                          │ │
│ │        messages = [                                                                          │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': '###\nRole name: default\nYou are Command Line App      │ │
│ │                   ShellGPT, a programming and syst'+335                                      │ │
│ │                   │   }                                                                      │ │
│ │                   ]                                                                          │ │
│ │          prompt = 'ascii emoji for shrug'                                                    │ │
│ │            self = <sgpt.handlers.default_handler.DefaultHandler object at                    │ │
│ │                   0x000001DBFF5ABE50>                                                        │ │
│ │            word = '¯'                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\remo\AppData\Roaming\Python\Python310\site-packages\sgpt\handlers\handler.py:23 in      │
│ get_completion                                                                                   │
│                                                                                                  │
│   20 │   │   raise NotImplementedError                                                           │
│   21 │                                                                                           │
│   22 │   def get_completion(self, **kwargs: Any) -> Generator[str, None, None]:                  │
│ ❱ 23 │   │   yield from self.client.get_completion(**kwargs)                                     │
│   24 │                                                                                           │
│   25 │   def handle(self, prompt: str, **kwargs: Any) -> str:                                    │
│   26 │   │   messages = self.make_messages(self.make_prompt(prompt))                             │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ kwargs = {                                                                                   │ │
│ │          │   'messages': [                                                                   │ │
│ │          │   │   {                                                                           │ │
│ │          │   │   │   'role': 'user',                                                         │ │
│ │          │   │   │   'content': '###\nRole name: default\nYou are Command Line App ShellGPT, │ │
│ │          a programming and syst'+335                                                         │ │
│ │          │   │   }                                                                           │ │
│ │          │   ],                                                                              │ │
│ │          │   'model': 'gpt-3.5-turbo',                                                       │ │
│ │          │   'temperature': 0.1,                                                             │ │
│ │          │   'top_probability': 1.0,                                                         │ │
│ │          │   'caching': True                                                                 │ │
│ │          }                                                                                   │ │
│ │   self = <sgpt.handlers.default_handler.DefaultHandler object at 0x000001DBFF5ABE50>         │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\remo\AppData\Roaming\Python\Python310\site-packages\sgpt\client.py:88 in get_completion │
│                                                                                                  │
│   85 │   │   :param caching: Boolean value to enable/disable caching.                            │
│   86 │   │   :return: String generated completion.                                               │
│   87 │   │   """                                                                                 │
│ ❱ 88 │   │   yield from self._request(                                                           │
│   89 │   │   │   messages,                                                                       │
│   90 │   │   │   model,                                                                          │
│   91 │   │   │   temperature,                                                                    │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │         caching = True                                                                       │ │
│ │        messages = [                                                                          │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': '###\nRole name: default\nYou are Command Line App      │ │
│ │                   ShellGPT, a programming and syst'+335                                      │ │
│ │                   │   }                                                                      │ │
│ │                   ]                                                                          │ │
│ │           model = 'gpt-3.5-turbo'                                                            │ │
│ │            self = <sgpt.client.OpenAIClient object at 0x000001DBFF5ABB20>                    │ │
│ │     temperature = 0.1                                                                        │ │
│ │ top_probability = 1.0                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\remo\AppData\Roaming\Python\Python310\site-packages\sgpt\cache.py:42 in wrapper         │
│                                                                                                  │
│   39 │   │   │   for i in func(*args, **kwargs):                                                 │
│   40 │   │   │   │   result += i                                                                 │
│   41 │   │   │   │   yield i                                                                     │
│ ❱ 42 │   │   │   cache_file.write_text(result)                                                   │
│   43 │   │   │   self._delete_oldest_files(self.length)  # type: ignore                          │
│   44 │   │                                                                                       │
│   45 │   │   return wrapper                                                                      │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       args = (                                                                               │ │
│ │              │   <sgpt.client.OpenAIClient object at 0x000001DBFF5ABB20>,                    │ │
│ │              │   [                                                                           │ │
│ │              │   │   {                                                                       │ │
│ │              │   │   │   'role': 'user',                                                     │ │
│ │              │   │   │   'content': '###\nRole name: default\nYou are Command Line App       │ │
│ │              ShellGPT, a programming and syst'+335                                           │ │
│ │              │   │   }                                                                       │ │
│ │              │   ],                                                                          │ │
│ │              │   'gpt-3.5-turbo',                                                            │ │
│ │              │   0.1,                                                                        │ │
│ │              │   1.0                                                                         │ │
│ │              )                                                                               │ │
│ │ cache_file = WindowsPath('C:/Users/mare/AppData/Local/Temp/shell_gpt/cache/8060251d7eddffb9… │ │
│ │  cache_key = '8060251d7eddffb984b24d1983e49fe7'                                              │ │
│ │       func = <function OpenAIClient._request at 0x000001DBFF5888B0>                          │ │
│ │          i = '¯'                                                                             │ │
│ │     kwargs = {}                                                                              │ │
│ │     result = '¯\\_(ツ)_/¯'                                                                   │ │
│ │       self = <sgpt.cache.Cache object at 0x000001DBFE651240>                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Program Files\Python310\lib\pathlib.py:1155 in write_text                                     │
│                                                                                                  │
│   1152 │   │   │   │   │   │   │   data.__class__.__name__)                                      │
│   1153 │   │   encoding = io.text_encoding(encoding)                                             │
│   1154 │   │   with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f  │
│ ❱ 1155 │   │   │   return f.write(data)                                                          │
│   1156 │                                                                                         │
│   1157 │   def readlink(self):                                                                   │
│   1158 │   │   """                                                                               │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │     data = '¯\\_(ツ)_/¯'                                                                     │ │
│ │ encoding = 'locale'                                                                          │ │
│ │   errors = None                                                                              │ │
│ │        f = <_io.TextIOWrapper                                                                │ │
│ │            name='C:\\Users\\remo\\AppData\\Local\\Temp\\shell_gpt\\cache\\8060251d7eddffb98… │ │
│ │            mode='w' encoding='cp1252'>                                                       │ │
│ │  newline = None                                                                              │ │
│ │     self = WindowsPath('C:/Users/mare/AppData/Local/Temp/shell_gpt/cache/8060251d7eddffb984… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Program Files\Python310\lib\encodings\cp1252.py:19 in encode                                  │
│                                                                                                  │
│    16                                                                                            │
│    17 class IncrementalEncoder(codecs.IncrementalEncoder):                                       │
│    18 │   def encode(self, input, final=False):                                                  │
│ ❱  19 │   │   return codecs.charmap_encode(input,self.errors,encoding_table)[0]                  │
│    20                                                                                            │
│    21 class IncrementalDecoder(codecs.IncrementalDecoder):                                       │
│    22 │   def decode(self, input, final=False):                                                  │
│                                                                                                  │
│ ╭────────────────────────────────── locals ──────────────────────────────────╮                   │
│ │ final = False                                                              │                   │
│ │ input = '¯\\_(ツ)_/¯'                                                      │                   │
│ │  self = <encodings.cp1252.IncrementalEncoder object at 0x000001DBFF5ABD90> │                   │
│ ╰────────────────────────────────────────────────────────────────────────────╯                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UnicodeEncodeError: 'charmap' codec can't encode character '\u30c4' in position 4: character maps to
<undefined>

**Comment by Remowylliams** [comment]
Maybe it was because I was using power shell not sure, 
So not sure if it's a bug or just expected.
this is using Shell-gpt 0.9 and python 3.10.9

**Comment by TheR1D** [comment]
This is definitely Windows related issue, since it works normal in my ZSH shell.

**Comment by iomari** [comment]
Same error in kubuntu 23.04 and zsh

**Comment by iomari** [comment]
It failed because I had switched to chatgpt 4. When I switched back to gpt-3.5-turbo it worked.
So why doesn't chat 4 work?

**Comment by moritz-t-w** [comment]
Related: #330

**Comment by TheR1D** [comment]
Closing this issue due to its age and the absence of similar reports.

**Comment by squirrelroad** [comment]
Hello, sorry to try to bring the issue back; I am facing the same `UnicodeEncodeError: 'charmap' codec can't encode characters in position 62-64:
character maps to <undefined>` reports when I ask to translate words to Japanese or Thai

**Comment by D0N-B0T** [comment]
They will never solve this issue. Bad luck

**Comment by TheR1D** [comment]
Should be fixed by https://github.com/TheR1D/shell_gpt/pull/737
