### ISSUE TITLE
feat: add azure openai support

### ISSUE THREAD

**Issue by jsburckhardt** [TheR1D/shell_gpt#203]
As a user of the project, I would like to request the addition of support for Azure OpenAI. With this new feature, I can take advantage of the advanced AI technologies and services offered by the Azure OpenAI platform.

I believe that incorporating support for Azure OpenAI would greatly enhance the project's functionality and usefulness. Users who are interested in integrating AI capabilities into their applications would find this feature particularly valuable.

Azure OpenAI already offers a range of APIs that are similar to those currently being used by the project. However, there are a few differences, which can be reviewed in detail at https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference.

For more information on how ChatGPT can be used in Azure OpenAI, please visit https://azure.microsoft.com/en-us/blog/chatgpt-is-now-available-in-azure-openai-service/.

**Comment by TheR1D** [comment]
I'm considering to use [LiteLLM](https://github.com/BerriAI/litellm) for multiple backends integration. This should provide an option to switch between various LLM backends including Azure. I would greatly appreciate any assistance with testing the Azure Integration PR https://github.com/TheR1D/shell_gpt/pull/463. To test it follow these steps:
```shell
git clone https://github.com/TheR1D/shell_gpt.git
cd shell_gpt
git checkout ollama
python -m venv venv
source venv/bin/activate
pip install -e  .

export AZURE_API_KEY=YOUR_KEY
export AZURE_API_BASE=YOUR_API_BASE
export AZURE_API_VERSION=YOUR_API_VERSION
export AZURE_AD_TOKEN=YOUR_TOKEN # Optional
export AZURE_API_TYPE=YOUR_API_TYPE # Optional

sgpt --model azure/<your_deployment_name> --no-functions "Hi Azure"
```

**Comment by TheR1D** [comment]
ShellGPT with LiteLLM was release as 1.3.0, please follow steps above to setup ShellGPT with Azure. Given that I'm closing this issue.

**Comment by nizametdinovcrx** [comment]
Any plans to update docs?

**Comment by TheR1D** [comment]
[Wiki page](https://github.com/TheR1D/shell_gpt/wiki/Azure) added, link included in README.md https://github.com/TheR1D/shell_gpt/pull/491
