### ISSUE TITLE
Error when trying to use gpt-4 model

### ISSUE THREAD

**Issue by fy2** [TheR1D/shell_gpt#210]
```bash
$ sgpt --model gpt-4  "colours of rainbow"
# (...)
HTTPError: 404 Client Error: Not Found for url: https://api.openai.com/v1/chat/completions

**Comment by akirataguchi115** [comment]
Are you subscribed to the ChatGPT Plus?

**Comment by fy2** [comment]
Yes

**Comment by fy2** [comment]
Does it work for you @akirataguchi115

**Comment by akirataguchi115** [comment]
I'm currently not subscribed to ChatGPT Plus. Does the path https://api.openai.com/v1/chat/completions on GET give you 404 on Browser f.ex.?

**Comment by TheR1D** [comment]
GPT4 is in private beta now, if you don't have access to private beta, you can't use it over API. ChatGPT Plus subrscription doesn't apply to API requests, it is only allows you to use GPT4 in browser on chat.openai.com

**Comment by fy2** [comment]
If I do it via the browser:

![image](https://user-images.githubusercontent.com/1507453/234095797-55a61e48-1933-4c53-8868-4b0aae54ab29.png)

but when doing it with `sgpt --model gpt-4  "colours of rainbow"` I still get the 404. Maybe the error I get is misleading from sgbt and there is something else going wrong

**Comment by fy2** [comment]
> GPT4 is in private beta now, if you don't have access to private beta, you can't use it over API. ChatGPT Plus subrscription doesn't apply to API requests, it is only allows you to use GPT4 in browser on chat.openai.com

all right, I pay for GPT4 but never used the API, always went to the browser chat..

**Comment by aemonge** [comment]
Does anyone here know how to request the private beta?

**Comment by aemonge** [comment]
Found it https://openai.com/waitlist/gpt-4
