### ISSUE TITLE
cost estimation rfc

### ISSUE THREAD

**Issue by hamidzr** [TheR1D/shell_gpt#216]
feature request: design a way to estimate query min-cost based on tokens, model, and published rates.

this can then be used to
- show query cost post execution
- confirm when estimated cost is higher than a set threshold before executing a request. this mainly helpful when piping output of other commands into sgpt

I'd be happy to work on this if there is interest.

Are there other related use cases and features you see? let me know

**Comment by TheR1D** [comment]
I think it would be better to use some external tool in order to calculate prompt tokens rather the have it as part of ShellGPT.
