### ISSUE TITLE
Generates an endless shell command

### ISSUE THREAD

**Issue by clstaudt** [TheR1D/shell_gpt#227]
Apparently I managed to trigger an infinite loop...  is this an AI safety feature? 😉

![6a50c3bb29d6aa1247d401bb42f7cec7d8aa7eecf1c508e3cba69755b91a8837](https://user-images.githubusercontent.com/875194/236537650-5a871198-858f-441e-9a3f-a3ae53bb09b7.jpg)

**Comment by TheR1D** [comment]
Since your prompt doesn't specify any specific details related to security, I believe GPT just throw every single package it knows related to pentesting. It is not perfect for every cases, that is the reason we have to check the output before executing :)

**Comment by clstaudt** [comment]
I believe endless generation indicates a deeper technical issue.
