### ISSUE TITLE
HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/chat/completions

### ISSUE THREAD

**Issue by mrAibo** [TheR1D/shell_gpt#229]
I provided the key, but:
{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by dwes7** [comment]
Same problem here. Saw this webpage and talks about backing off the request by adding a small timeout and resending. Does sgpt do that or have a configuration for this? Might be a good task if not. https://help.openai.com/en/articles/5955604-how-can-i-solve-429-too-many-requests-errors

**Comment by TheR1D** [comment]
https://github.com/TheR1D/shell_gpt/issues/201
