### ISSUE TITLE
executed shell commands generated should be added to the terminal's history

### ISSUE THREAD

**Issue by joeyda3rd** [TheR1D/shell_gpt#233]

**Comment by adilansari488** [comment]
We cannot directly add generated commands by sgpt into shell history. However, I figured out an approach for storing commands in terminal history. In my approach, terminal history will be available if the current terminal session is successfully logged out (exited). Then in the new session, the history from sgpt generated commands will also be there.

**Comment by joeyda3rd** [comment]
You can manipulate the current session's history using the history command.  The history -s command allows you to add an entry to the current session's history. Here's an example:

`history -s "echo Hello, world!"`

This script will add the command echo Hello, world! to the current session's history, and it will appear when you press the up arrow or use the history command.

If you want to permanently add commands to the bash history file (.bash_history), you can append commands to it like any other file. For example:

`echo "echo Hello, world!" >> ~/.bash_history`

This will append the command to the .bash_history file, but as mentioned earlier, it won't appear in the current session's history until a new session is started or the history is manually reloaded with history -r.

**Comment by joeyda3rd** [comment]
While a child process (like a script) cannot directly modify the history of its parent process (like a shell session), there are a few workarounds you could consider:

1. Have the user source a script: You could generate a Bash script, and then instruct the user to source this script in their shell. This would execute the commands in the same shell session and add them to the shell's history.

2. Use a custom history file: You could have your Python script write the commands to a custom history file. Then, in your shell, you could use the history -r command to read this file and add its contents to the current shell history. Here's how you could do this:

```# Python script
with open("custom_history", "w") as history_file:
    history_file.write("echo Hello, world!\n")
```

Then, in the shell:

```
'history -r custom_history'
```

3. Use an alias or function: You could set up an alias or function in your shell that runs the Python script and then sources a script generated by the Python script. This would need to be set up in your .bashrc or .bash_profile file. Here's an example:

```
alias run_python_and_source='python3 my_script.py && source generated_commands.sh'
```

With this alias, running run_python_and_source would run your Python script and then source the generated_commands.sh script in the same shell session.

All of these workarounds have their limitations, and none of them can fully automate the process of adding commands to the history of an arbitrary, already-running shell session.
