### ISSUE TITLE
Installation Error for Ubuntu 22.04 - could not find a version that satisfies the requirements

### ISSUE THREAD

**Issue by iguelkanat** [TheR1D/shell_gpt#236]
Hi,

I am trying to install shell-gtp on Ubuntu 22.04 with Python 3.10.6 but I get allways the error message that it could not be found a version that satisfies the requirement shell-gtp (no matter which version I try to install).

What do I miss?

**Comment by primal100** [comment]
It's underscore in shell_gpt, not dash
