### ISSUE TITLE
Make it reflect on it's output before running

### ISSUE THREAD

**Issue by thibaultmol** [TheR1D/shell_gpt#243]
I've noticed that sometimes the command it generates is wrong. BUT if I then ask gpt(4). "verify that this command is correct according to this description 'prompt': 'sgpt-output' "

I don't mind paying the extra api calls to basically have certain more complicated commands be run trough, twice, like this. just to be sure they're correct. Cause everytime it's been able to fix the command to exactly what I want

**Comment by Oddly** [comment]
I would like to see this as well. It would be nice to be able to see GPT try its own script, evaluate what is wrong and then correct it. Being able to configure several iterations of this would be a nice bonus.

**Comment by TheR1D** [comment]
I think this is possible just by using pipes, which could be used with some alias: `sgpt -s "using docker create postgres container" | sgpt -s "fix the shell command"`
