### ISSUE TITLE
Bug report? and param --version request

### ISSUE THREAD

**Issue by sur1v** [TheR1D/shell_gpt#251]
I've been using it lately and is very cool, thanks for sharing it.

I have implemented locally using my own build docker image, from latest version (0.9.1), directly from source. This is my .profile:
```
alias sgpt="docker run --rm --env OPENAI_API_KEY --volume gpt-cache:/tmp/shell_gpt shellgpt"
export OPENAI_API_KEY="changeme"
```
It seems to work properly:
```
$ sgpt "tell me rainbow colors as if you were under daltonism"
Sure, as someone with daltonism, I see the colors of the rainbow differently than someone without it. The colors I see are red, greenish-yellow, green, blue, purple, and pinkish-orange.
```
However when I pipe an action like a diff for a commit message, it fails:
```
$ git diff
diff --git a/Dockerfile b/Dockerfile
index 8ba8544..efdd667 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,13 +1,25 @@
-FROM python:3-alpine
+FROM python:3.9-slim
...
$ git diff | sgpt "Generate git commit message, for my changes"
Sure, what are the changes you made?
```
I guess is not piping the diff into the container? How can we fix this?

Also, would be great to have a --version param to be sure what version I'm using. Thanks again!

**Comment by TheR1D** [comment]
Although I'm not aware of a straightforward method to pipe data into a container, it's still possible to use arguments. Here's an example:
```shell
sgpt "Generate a git commit message for my changes: $(git diff)"
```
