### ISSUE TITLE
Node upgrade failed

### ISSUE THREAD

**Issue by aetherwu** [TheR1D/shell_gpt#253]
```
sgpt --shell "upgrade nodejs to latest version
dquote> "
brew upgrade node
[E]xecute, [D]escribe, [A]bort: e
==> Downloading https://formulae.brew.sh/api/formula.jws.json
-#O=-#      #        #
==> Downloading https://formulae.brew.sh/api/cask.jws.json
-#O=-#      #        #
Error: node not installed
```

Node was installed properly:
```
node -v
v14.15.4
```

**Comment by TheR1D** [comment]
I suspect that Node on your system was not installed using Brew, which is likely causing Brew to generate this error. However, this isn't an issue related to Shell GPT rather, it seems to be system-related. In this case, Shell GPT just suggests a command.
