### ISSUE TITLE
CACHE_PATH and CHAT_CACHE_PATH var issues in a multiuser system.

### ISSUE THREAD

**Issue by shellclear** [TheR1D/shell_gpt#256]
When different users run the program the default value of the CACHE_PATH and CHAT_CACHE_PATH var appoint to the same folder inside _/tmp /cache_ directory generating perms issues.

The program should create a cache folder for each user inside /tmp directory.

**Comment by TheR1D** [comment]
These changes will cause all current users to lose their chat sessions and cache. May be safe solution in this case would be to edit `CHAT_CACHE_PATH` and `CACHE_PATH` in `.sgptrc` per user manually.
