### ISSUE TITLE
Continuous chat mode

### ISSUE THREAD

**Issue by Microwave-WYB** [TheR1D/shell_gpt#260]
It's a pain having to rewrite all the command line flags each time. Can wwe add a continuous chat mode so that you can chat with only one command?
For example:
```
$ sgpt --chat demo --continuous
>>> How can you help me?
Blablablabla
>>> What's the mass of sun?
Blablabla
```

**Comment by AmShaegar13** [comment]
Did you try `--repl`?

**Comment by TheR1D** [comment]
Yes, `--repl` can do it.
