### ISSUE TITLE
FEATURE REQUEST: Works with llama.cpp/llama-cpp-python BUT need to pass extra JSON

### ISSUE THREAD

**Issue by Free-Radical** [TheR1D/shell_gpt#276]
FIRSTLY,  AWESOME REPO, LOVE IT!!!

Since llama.cpp/llama-cpp-python can run a huge number of llama etc models on an API that basically mimics OpenAI's API, we can run  sgpt for free with any model
**I tested it and it works** !!! Yea 🥳 
BUT we need to be able to pass some extra JSON values at times depending on the model.

FEATURE REQUEST: spgt needs a modification in the config file that allows extra JSON settings per model. etc.
This project (https://github.com/charmbracelet/mods#settings)  has such a feature already, but its written in GO. 

BTW some of these freely available models are extreme;y good

**Comment by will-wright-eng** [comment]
I'd be curious to see how you got this working! Any code you can share?

Also, I believe you can make go libraries available to python through [ctypes](https://docs.python.org/3/library/ctypes.html)...

**Comment by Free-Radical** [comment]
@will-wright-eng i presume you mean how I got lama-cpp-python web api working with sgpt?
If yes, relatively simple:

(Assuming Linux, don't do windoze)
1. pip install llama-cpp-python
2. Read WEB Server section on  https://pypi.org/project/llama-cpp-python/
3. Run Web Server as instructed & confirm per example
4. Edit ~/.config/shell_gpt/.sgptrc 
5. Change OPENAPI_API_HOST=http://localhost:8000
(Or whatever port your llama API running)

Cli should work now, be advised you need a good model to get good results.
