### ISSUE TITLE
Documentation Request: How is `chat` different from `repl`?

### ISSUE THREAD

**Issue by startakovsky** [TheR1D/shell_gpt#282]
I would love to add a section to the README to answer this question:

> How is chat different from repl?

Please help me to understand, we can refine the explanation in this issue.

**Comment by jacmuckyck** [comment]
I think they're the same, just with a different interface

REPL is the way to go. Even with an alias, if if you're trying to have a back and forth conversation, `sgpt --chat holiday_suggestions "My prompt here"` is just too cumbersome when REPL is available

**Comment by startakovsky** [comment]
Yeah, perhaps we want to make it explicit? See above draft PR.
