### ISSUE TITLE
When you integrate gpt-3.5-turbo-16k?

### ISSUE THREAD

**Issue by andresrex** [TheR1D/shell_gpt#283]
I was hoping to use this already but I see it is not available

**Comment by 00-Python** [comment]
I [dont think it will be added](https://github.com/TheR1D/shell_gpt/pull/263#discussion_r1225417744), there is a [pull request pending](https://github.com/TheR1D/shell_gpt/pull/277) by somebody but, you can add it simply by opening the file ```sgpt/utils.py``` and add this line of code ```  GPT3_16k = "gpt-3.5-turbo-16k" ```

![image](https://github.com/TheR1D/shell_gpt/assets/8343312/0221c959-b092-4d52-8515-22214bfc6289)
