### ISSUE TITLE
shell-gpt dependencies

### ISSUE THREAD

**Issue by error467** [TheR1D/shell_gpt#288]
Can anyone tell me why there is so many package its missing like rich and request?  I tried to install those package on range but to no avail.  Kindly help.  Im running Centos 7.9. TIA

Using cached shell_gpt-0.7.0-py3-none-any.whl (12 kB)
  Using cached shell_gpt-0.6.0-py3-none-any.whl (6.4 kB)
  Using cached shell_gpt-0.5.1-py3-none-any.whl (6.5 kB)
  Using cached shell_gpt-0.5.0-py3-none-any.whl (6.1 kB)
  Using cached shell_gpt-0.4.1-py3-none-any.whl (5.3 kB)
  Using cached shell_gpt-0.4.tar.gz (4.8 kB)
  Preparing metadata (setup.py) ... done
  Using cached shell_gpt-0.3.tar.gz (4.8 kB)
  Preparing metadata (setup.py) ... done
  Using cached shell_gpt-0.2.tar.gz (4.8 kB)
  Preparing metadata (setup.py) ... done
  Using cached shell_gpt-0.1.tar.gz (4.8 kB)
  Preparing metadata (setup.py) ... done
ERROR: Cannot install shell-gpt==0.1, shell-gpt==0.2, shell-gpt==0.3, shell-gpt==0.4, shell-gpt==0.4.1, shell-gpt==0.5.0, shell-gpt==0.5.1, shell-gpt==0.6.0, shell-gpt==0.7.0, shell-gpt==0.7.1, shell-gpt==0.7.3, shell-gpt==0.8.0, shell-gpt==0.8.1, shell-gpt==0.8.2, shell-gpt==0.8.3, shell-gpt==0.8.4, shell-gpt==0.8.5, shell-gpt==0.8.6, shell-gpt==0.8.7, shell-gpt==0.8.8, shell-gpt==0.8.9, shell-gpt==0.9.0, shell-gpt==0.9.1, shell-gpt==0.9.2 and shell-gpt==0.9.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    shell-gpt 0.9.3 depends on rich<14.0.0 and >=13.1.0
    shell-gpt 0.9.2 depends on rich<14.0.0 and >=13.1.0
    shell-gpt 0.9.1 depends on rich<14.0.0 and >=13.1.0
    shell-gpt 0.9.0 depends on requests<3.0.0 and >=2.28.2
    shell-gpt 0.8.9 depends on requests<3.0.0 and >=2.28.2
    shell-gpt 0.8.8 depends on requests~=2.28.2
    shell-gpt 0.8.7 depends on requests~=2.28.2
    shell-gpt 0.8.6 depends on requests~=2.28.2
    shell-gpt 0.8.5 depends on requests~=2.28.2
    shell-gpt 0.8.4 depends on requests~=2.28.2
    shell-gpt 0.8.3 depends on requests~=2.28.2
    shell-gpt 0.8.2 depends on requests~=2.28.2
    shell-gpt 0.8.1 depends on requests~=2.28.2
    shell-gpt 0.8.0 depends on requests~=2.28.2
    shell-gpt 0.7.3 depends on requests~=2.28.2
    shell-gpt 0.7.1 depends on requests~=2.28.2
    shell-gpt 0.7.0 depends on requests~=2.28.2
    shell-gpt 0.6.0 depends on requests~=2.28.2
    shell-gpt 0.5.1 depends on requests~=2.28.2
    shell-gpt 0.5.0 depends on requests~=2.28.2
    shell-gpt 0.4.1 depends on requests~=2.28.2
    shell-gpt 0.4 depends on requests~=2.28.2
    shell-gpt 0.3 depends on requests~=2.28.2
    shell-gpt 0.2 depends on requests~=2.28.2
    shell-gpt 0.1 depends on requests~=2.28.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by Lovening** [comment]
I also have this problem. The system is ubuntu18.04 and the python3 version is 3.6.9

**Comment by David-Else** [comment]
I used `pipx` with no problems, it is in the Debian 12 stable repo.

> pipx — Install and Run Python Applications in Isolated Environments
