### ISSUE TITLE
it's not working in wsl ubuntu 22 after installing it didn't redirected to chagpt login

### ISSUE THREAD

**Issue by tanmay-veer** [TheR1D/shell_gpt#29]
![image](https://user-images.githubusercontent.com/101004444/219971822-5829c8c0-b79d-484c-8129-756d241ec26e.png)

**Comment by TheR1D** [comment]
The installation process is just installing a Python package on the machine, it doesn't do any thing more than that. To use is it, call `sgpt "your prompt"` and it will ask your API key. You can generate your API key [here](https://beta.openai.com/account/api-keys).
