### ISSUE TITLE
statically compiled binary

### ISSUE THREAD

**Issue by YahiaJr** [TheR1D/shell_gpt#291]
I have a portable shell environment that contains lots of statically compiled binaries, and I bring it to multiple machines/servers that I mange regularly. I can encounter a system that doesn't necessarily has python installed nor have internet connection/admin privileges to install it.

Is there a way to build shell_gpt into a single binary file that I can run on different machines without dependency issues?

I know that I won't be able to use it without internet anyways, but it would be helpful to have it nonetheless if its possible.

So, if you don't have the time to add it in next release, could you point me how to build it myself.

Thank you

**Comment by TheR1D** [comment]
You can build `sgpt` into a single binary file using [pyinstaller](https://pypi.org/project/pyinstaller/). It will include all dependencies along with the Python interpreter, dynamically linked libraries, and the app into a single package.
```shell
git clone https://github.com/TheR1D/shell_gpt.git
cd shell_gpt
python3 -m venv venv
source venv/bin/activate
pip install pyinstaller
pip install -e .
cd sgpt
pyinstaller --onefile app.py
```
This process generates a "dist" directory containing the binary file "app" that you can execute with `./app --help`.

Please note:
* The binary will be compatible with the operating system and architecture you compile it on. For example, if you compile your Python script into a binary on a Linux machine, the resulting binary will only be compatible with Linux.
* This method may lead to significant performance degradation.

**Comment by YahiaJr** [comment]
THANK YOU... 🙏
