### ISSUE TITLE
I get error messages like this even if I increase chat_cache in .sgptrc

### ISSUE THREAD

**Issue by bitcoinmeetups** [TheR1D/shell_gpt#297]
Hi,

I'm Mr. Table, a very friendly guy.

I get error messages like this one even if I increase chat_cache in .sgptrc. Any fix?

│ │           model = 'gpt-3.5-turbo'                                      │ │
│ │        response = <Response [400]>                                     │ │
│ │            self = <sgpt.client.OpenAIClient object at 0x7fb9981fa0>    │ │
│ │     temperature = 0.1                                                  │ │
│ │ top_probability = 1.0                                                  │ │
│ ╰────────────────────────────────────────────────────────────────────────╯ │
│                                                                            │
│ /home/pi/.local/lib/python3.9/site-packages/requests/models.py:1021 in     │
│ raise_for_status                                                           │
│                                                                            │
│   1018 │   │   │   )                                                       │
│   1019 │   │                                                               │
│   1020 │   │   if http_error_msg:                                          │
│ ❱ 1021 │   │   │   raise HTTPError(http_error_msg, response=self)          │
│   1022 │                                                                   │
│   1023 │   def close(self):                                                │
│   1024 │   │   """Releases the connection back to the pool. Once this meth │
│                                                                            │
│ ╭──────────────────────────────── locals ────────────────────────────────╮ │
│ │ http_error_msg = '400 Client Error: Bad Request for url:               │ │
│ │                  https://api.openai.com/v1/chat/completion'+1          │ │
│ │         reason = 'Bad Request'                                         │ │
│ │           self = <Response [400]>                                      │ │
│ ╰────────────────────────────────────────────────────────────────────────╯ │
╰────────────────────────────────────────────────────────────────────────────╯
HTTPError: 400 Client Error: Bad Request for url:
https://api.openai.com/v1/chat/completions
4>

**Comment by 00-Python** [comment]
How large is the text that you are inputting? and what model are you using?

**Comment by bitcoinmeetups** [comment]
It's a large text. However according to this blog post they have updated the context version to 16k for turbo 3.5 so it should fit:

https://openai.com/blog/function-calling-and-other-api-updates

I was going to post that before I read your reply and now I see that we have the same idea. I will try to use the flag you suggested this time.

**Comment by bitcoinmeetups** [comment]
Seems like this flag is not working. Example:

4> echo hello | sgpt --model gpt-3.5-turbo-16k --chat $(date +%Y%m%d%H) 2>/dev
/null
No output here

4> echo hello | sgpt --chat $(date +%Y%m%d%H) 2>/dev/null
Hello! How can I assist you today?
4>

**Comment by bitcoinmeetups** [comment]
Tried updating sgpt using pip but I still get:

4> sgpt --chat test123 --model gpt-3.5-turbo-16k "hello"
Usage: sgpt [OPTIONS] [PROMPT]
Try 'sgpt --help' for help.
╭─ Error ────────────────────────────────────────────────────────────────────╮
│ Invalid value for '--model': 'gpt-3.5-turbo-16k' is not one of             │
│ 'gpt-3.5-turbo', 'gpt-4', 'gpt-4-32k'.                                     │
╰────────────────────────────────────────────────────────────────────────────╯
4>

**Comment by 00-Python** [comment]
My apologies as per the readme they uses the flag `--model gpt-3.5-16k`

**Comment by TheR1D** [comment]
To get larger token window for your prompt use `gpt-4-1106-preview` model which allows 128,000 tokens. This model will be set as a default for ShellGPT soon.
