### ISSUE TITLE
Enhance cache capability

### ISSUE THREAD

**Issue by SimFG** [TheR1D/shell_gpt#299]
great project. This will reduce the time I spend looking up information so I can get off work faster!!!

Try accessing the [GPTCache](https://github.com/zilliztech/GPTCache) feature, which can help avoid multiple requests to OpenAI for similar queries, leading to faster responses and reduced usage costs.

I hope that this will help make the project more appealing.

**Comment by TheR1D** [comment]
ShellGPT has its own implemented cache.
