### ISSUE TITLE
Implement API key reset option

### ISSUE THREAD

**Issue by TheR1D** [TheR1D/shell_gpt#30]
Implement an option to reset an API key using command line argument `--reset-key`. When user provides this flag delete file located in `~/.config/shell-gpt/api_key.txt` and ask for new API key. Additionally impement API key validation. Since OpenAI doesn't have dedicated endpoint just for key validation, call `https://api.openai.com/v1/completions` with some test prompt, make sure response status code is not 403, if so, ask user for valid API key.

**Comment by highonweb** [comment]
Hey I messed up and I pasted my API key twice, do you need help with this feature

**Comment by TheR1D** [comment]
@highonweb solution for now: https://github.com/TheR1D/shell_gpt/issues/5

**Comment by highonweb** [comment]
Thanks bro. Got it

**Comment by m4l490n** [comment]
> @highonweb solution for now: #5

That doesn't work. There is no `.config/shell-gpt/api_key.txt` and reinstalling doesn't work for having shell-gpt ask for the key again. I can't make it ask for the key again.
