### ISSUE TITLE
Add base URL option

### ISSUE THREAD

**Issue by alexkreidler** [TheR1D/shell_gpt#303]
There are various open source models and hosted LLMOps tools that are compatible with the OpenAI API, like [LocalAI](https://github.com/go-skynet/LocalAI) and [Helicone](https://helicone.ai/). Langchain has had an option called `OPENAI_API_BASE` (in python and via an environment variable) [for three months](https://github.com/hwchase17/langchain/commit/4f231b46eeb99b680964d5799f2384edfa2913e2). It would be great to be able to use ShellGPT with these systems! This is slightly related to #302 but different.

**Comment by alexkreidler** [comment]
Whoops I realized it is included here, but under the name `OPENAI_API_HOST`. Might be worth using the same name as Langchain's option for consistency and so people with `.env` files don't need to change them.

**Comment by cori** [comment]
I'll second this - I have both values set in my env for this very reason (not LanChain but another tool that uses `OPENAAPI_BASE`). As a loose and unreliable measure, GitHub search seems to aggree that `_BASE` is more..."popular"

![image](https://github.com/TheR1D/shell_gpt/assets/46317/9f5afd84-6163-49d0-baa9-9073d3d7372f)

[`OPENAI_API_BASE` Code search results](https://github.com/search?q=OPENAI_API_BASE&type=code)

![image](https://github.com/TheR1D/shell_gpt/assets/46317/412932f5-6a29-4c4d-b23a-898cd877c26f)


[`OPENAI_API_HOST` Code search results](https://github.com/search?q=OPENAI_API_HOST&type=code)

**Comment by TheR1D** [comment]
Implemented.
