### ISSUE TITLE
Allow for more than one temp session at a time

### ISSUE THREAD

**Issue by julianbarg** [TheR1D/shell_gpt#305]
Currently, shell_gpt is limited by how temp sessions are implemented. If you have a REPL session going and use a temp session elsewhere, your REPL session is overwritten, and the cache is lost. More suitable approach (for linux) would be to store each temp session in /tmp as a separate file.

**Comment by TheR1D** [comment]
If we want to save the conversation it is better to give it meaningful name, and it will be saved, e.g. `sgpt --repl important_conversation`.
