### ISSUE TITLE
sgpt -s does not use my functions

### ISSUE THREAD

**Issue by agarrubio** [TheR1D/shell_gpt#306]
I work in zsh. The folowing request offers to execute a command but fails:
```
sgpt -s "print filename, then apply 'head -1 |nh' to all '.tsv' in current dir"
```
It proposes the right answer:
```
for file in *.tsv; do echo $file; head -1 $file | nh; done
```
If I run it myself, every thing is OK! But if sgpt runs it (option 'E'), I get this error:
```
zsh:1: command not found: nh
head: write error: Broken pipe
```
Of course, nh is a zsh function I had defined.

**Comment by TheR1D** [comment]
Should be fixed in one of previous releases.
