### ISSUE TITLE
Not working !! 

### ISSUE THREAD

**Issue by milesdredd** [TheR1D/shell_gpt#311]
i have installed shell gpt 3 months ago , it was running fine , but after that i got a error "Too many request ..."
so i uninstalled it ,because i couldn't solve the problem.
but even after reinstalling , and performing everything said by [this link](https://beebom.com/how-use-chatgpt-linux-terminal/)
i have the same issue .
pls help me , 
i am on kde plasma (ubuntu version)

error :

` (gpt) milesdredd@milesdredd-k-notebook:~/chat$ sgpt --chat joke "can you tell me a joke?"
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/milesdredd/.local/lib/python3.10/site-packages/sgpt/app.py:158 in main                     │
│                                                                                                  │
│   155 │   │   )                                                                                  │
│   156 │                                                                                          │
│   157 │   if chat:                                                                               │
│ ❱ 158 │   │   full_completion = ChatHandler(chat, role_class).handle(                            │
│   159 │   │   │   prompt,                                                                        │
│   160 │   │   │   model=model,                                                                   │
│   161 │   │   │   temperature=temperature,                                                       │
│                                                                                                  │
│ ╭─────────────────────────────── locals ────────────────────────────────╮                        │
│ │               cache = True                                            │                        │
│ │                chat = 'joke'                                          │                        │
│ │                code = False                                           │                        │
│ │         create_role = None                                            │                        │
│ │      describe_shell = False                                           │                        │
│ │              editor = False                                           │                        │
│ │ install_integration = None                                            │                        │
│ │          list_chats = None                                            │                        │
│ │          list_roles = None                                            │                        │
│ │               model = 'gpt-3.5-turbo'                                 │                        │
│ │              prompt = 'can you tell me a joke?'                       │                        │
│ │                repl = None                                            │                        │
│ │                role = None                                            │                        │
│ │          role_class = <sgpt.role.SystemRole object at 0x7fb864012ef0> │                        │
│ │               shell = False                                           │                        │
│ │           show_chat = None                                            │                        │
│ │           show_role = None                                            │                        │
│ │        stdin_passed = False                                           │                        │
│ │         temperature = 0.1                                             │                        │
│ │     top_probability = 1.0                                             │                        │
│ ╰───────────────────────────────────────────────────────────────────────╯                        │
│                                                                                                  │
│ /home/milesdredd/.local/lib/python3.10/site-packages/sgpt/handlers/handler.py:33 in handle       │
│                                                                                                  │
│   30 │   │   stream = cfg.get("DISABLE_STREAMING") == "false"                                    │
│   31 │   │   if not stream:                                                                      │
│   32 │   │   │   typer.echo("Loading...\r", nl=False)                                            │
│ ❱ 33 │   │   for word in self.get_completion(messages=messages, **kwargs):                       │
│   34 │   │   │   typer.secho(word, fg=self.color, bold=True, nl=False)                           │
│   35 │   │   │   full_completion += word                                                         │
│   36 │   │   typer.echo("\033[K" if not stream else "")  # Overwrite "loading..."                │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ full_completion = ''                                                                         │ │
│ │          kwargs = {                                                                          │ │
│ │                   │   'model': 'gpt-3.5-turbo',                                              │ │
│ │                   │   'temperature': 0.1,                                                    │ │
│ │                   │   'top_probability': 1.0,                                                │ │
│ │                   │   'chat_id': 'joke',                                                     │ │
│ │                   │   'caching': True                                                        │ │
│ │                   }                                                                          │ │
│ │        messages = [                                                                          │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': '###\nRole name: default\nYou are Command Line App      │ │
│ │                   ShellGPT, a programming and syst'+341                                      │ │
│ │                   │   }                                                                      │ │
│ │                   ]                                                                          │ │
│ │          prompt = 'can you tell me a joke?'                                                  │ │
│ │            self = <sgpt.handlers.chat_handler.ChatHandler object at 0x7fb864013430>          │ │
│ │          stream = True                                                                       │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/milesdredd/.local/lib/python3.10/site-packages/sgpt/handlers/chat_handler.py:53 in wrapper │
│                                                                                                  │
│    50 │   │   │   │   old_messages.append(message)                                               │
│    51 │   │   │   kwargs["messages"] = old_messages                                              │
│    52 │   │   │   response_text = ""                                                             │
│ ❱  53 │   │   │   for word in func(*args, **kwargs):                                             │
│    54 │   │   │   │   response_text += word                                                      │
│    55 │   │   │   │   yield word                                                                 │
│    56 │   │   │   old_messages.append({"role": "assistant", "content": response_text})           │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │          args = (<sgpt.handlers.chat_handler.ChatHandler object at 0x7fb864013430>,)         │ │
│ │       chat_id = 'joke'                                                                       │ │
│ │          func = <function ChatHandler.get_completion at 0x7fb864041510>                      │ │
│ │        kwargs = {                                                                            │ │
│ │                 │   'messages': [                                                            │ │
│ │                 │   │   {                                                                    │ │
│ │                 │   │   │   'role': 'user',                                                  │ │
│ │                 │   │   │   'content': '###\nRole name: default\nYou are Command Line App    │ │
│ │                 ShellGPT, a programming and syst'+341                                        │ │
│ │                 │   │   }                                                                    │ │
│ │                 │   ],                                                                       │ │
│ │                 │   'model': 'gpt-3.5-turbo',                                                │ │
│ │                 │   'temperature': 0.1,                                                      │ │
│ │                 │   'top_probability': 1.0,                                                  │ │
│ │                 │   'caching': True                                                          │ │
│ │                 }                                                                            │ │
│ │       message = {                                                                            │ │
│ │                 │   'role': 'user',                                                          │ │
│ │                 │   'content': '###\nRole name: default\nYou are Command Line App ShellGPT,  │ │
│ │                 a programming and syst'+341                                                  │ │
│ │                 }                                                                            │ │
│ │      messages = [                                                                            │ │
│ │                 │   {                                                                        │ │
│ │                 │   │   'role': 'user',                                                      │ │
│ │                 │   │   'content': '###\nRole name: default\nYou are Command Line App        │ │
│ │                 ShellGPT, a programming and syst'+341                                        │ │
│ │                 │   }                                                                        │ │
│ │                 ]                                                                            │ │
│ │  old_messages = [                                                                            │ │
│ │                 │   {                                                                        │ │
│ │                 │   │   'role': 'user',                                                      │ │
│ │                 │   │   'content': '###\nRole name: default\nYou are Command Line App        │ │
│ │                 ShellGPT, a programming and syst'+341                                        │ │
│ │                 │   }                                                                        │ │
│ │                 ]                                                                            │ │
│ │ response_text = ''                                                                           │ │
│ │          self = <sgpt.handlers.chat_handler.ChatSession object at 0x7fb864fa0580>            │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/milesdredd/.local/lib/python3.10/site-packages/sgpt/handlers/chat_handler.py:179 in        │
│ get_completion                                                                                   │
│                                                                                                  │
│   176 │   │   self,                                                                              │
│   177 │   │   **kwargs: Any,                                                                     │
│   178 │   ) -> Generator[str, None, None]:                                                       │
│ ❱ 179 │   │   yield from super().get_completion(**kwargs)                                        │
│   180                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ kwargs = {                                                                                   │ │
│ │          │   'messages': [                                                                   │ │
│ │          │   │   {                                                                           │ │
│ │          │   │   │   'role': 'user',                                                         │ │
│ │          │   │   │   'content': '###\nRole name: default\nYou are Command Line App ShellGPT, │ │
│ │          a programming and syst'+341                                                         │ │
│ │          │   │   }                                                                           │ │
│ │          │   ],                                                                              │ │
│ │          │   'model': 'gpt-3.5-turbo',                                                       │ │
│ │          │   'temperature': 0.1,                                                             │ │
│ │          │   'top_probability': 1.0,                                                         │ │
│ │          │   'caching': True                                                                 │ │
│ │          }                                                                                   │ │
│ │   self = <sgpt.handlers.chat_handler.ChatHandler object at 0x7fb864013430>                   │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/milesdredd/.local/lib/python3.10/site-packages/sgpt/handlers/handler.py:25 in              │
│ get_completion                                                                                   │
│                                                                                                  │
│   22 │   │   raise NotImplementedError                                                           │
│   23 │                                                                                           │
│   24 │   def get_completion(self, **kwargs: Any) -> Generator[str, None, None]:                  │
│ ❱ 25 │   │   yield from self.client.get_completion(**kwargs)                                     │
│   26 │                                                                                           │
│   27 │   def handle(self, prompt: str, **kwargs: Any) -> str:                                    │
│   28 │   │   messages = self.make_messages(self.make_prompt(prompt))                             │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ kwargs = {                                                                                   │ │
│ │          │   'messages': [                                                                   │ │
│ │          │   │   {                                                                           │ │
│ │          │   │   │   'role': 'user',                                                         │ │
│ │          │   │   │   'content': '###\nRole name: default\nYou are Command Line App ShellGPT, │ │
│ │          a programming and syst'+341                                                         │ │
│ │          │   │   }                                                                           │ │
│ │          │   ],                                                                              │ │
│ │          │   'model': 'gpt-3.5-turbo',                                                       │ │
│ │          │   'temperature': 0.1,                                                             │ │
│ │          │   'top_probability': 1.0,                                                         │ │
│ │          │   'caching': True                                                                 │ │
│ │          }                                                                                   │ │
│ │   self = <sgpt.handlers.chat_handler.ChatHandler object at 0x7fb864013430>                   │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/milesdredd/.local/lib/python3.10/site-packages/sgpt/client.py:98 in get_completion         │
│                                                                                                  │
│    95 │   │   :param caching: Boolean value to enable/disable caching.                           │
│    96 │   │   :return: String generated completion.                                              │
│    97 │   │   """                                                                                │
│ ❱  98 │   │   yield from self._request(                                                          │
│    99 │   │   │   messages,                                                                      │
│   100 │   │   │   model,                                                                         │
│   101 │   │   │   temperature,                                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │         caching = True                                                                       │ │
│ │        messages = [                                                                          │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': '###\nRole name: default\nYou are Command Line App      │ │
│ │                   ShellGPT, a programming and syst'+341                                      │ │
│ │                   │   }                                                                      │ │
│ │                   ]                                                                          │ │
│ │           model = 'gpt-3.5-turbo'                                                            │ │
│ │            self = <sgpt.client.OpenAIClient object at 0x7fb864012e00>                        │ │
│ │     temperature = 0.1                                                                        │ │
│ │ top_probability = 1.0                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/milesdredd/.local/lib/python3.10/site-packages/sgpt/cache.py:39 in wrapper                 │
│                                                                                                  │
│   36 │   │   │   │   yield cache_file.read_text()                                                │
│   37 │   │   │   │   return                                                                      │
│   38 │   │   │   result = ""                                                                     │
│ ❱ 39 │   │   │   for i in func(*args, **kwargs):                                                 │
│   40 │   │   │   │   result += i                                                                 │
│   41 │   │   │   │   yield i                                                                     │
│   42 │   │   │   cache_file.write_text(result)                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       args = (                                                                               │ │
│ │              │   <sgpt.client.OpenAIClient object at 0x7fb864012e00>,                        │ │
│ │              │   [                                                                           │ │
│ │              │   │   {                                                                       │ │
│ │              │   │   │   'role': 'user',                                                     │ │
│ │              │   │   │   'content': '###\nRole name: default\nYou are Command Line App       │ │
│ │              ShellGPT, a programming and syst'+341                                           │ │
│ │              │   │   }                                                                       │ │
│ │              │   ],                                                                          │ │
│ │              │   'gpt-3.5-turbo',                                                            │ │
│ │              │   0.1,                                                                        │ │
│ │              │   1.0                                                                         │ │
│ │              )                                                                               │ │
│ │ cache_file = PosixPath('/tmp/cache/3fa01baa2681180098544ea5cdfa405a')                        │ │
│ │  cache_key = '3fa01baa2681180098544ea5cdfa405a'                                              │ │
│ │       func = <function OpenAIClient._request at 0x7fb864040790>                              │ │
│ │     kwargs = {}                                                                              │ │
│ │     result = ''                                                                              │ │
│ │       self = <sgpt.cache.Cache object at 0x7fb864fa07f0>                                     │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/milesdredd/.local/lib/python3.10/site-packages/sgpt/client.py:61 in _request               │
│                                                                                                  │
│    58 │   │   │   timeout=REQUEST_TIMEOUT,                                                       │
│    59 │   │   │   stream=stream,                                                                 │
│    60 │   │   )                                                                                  │
│ ❱  61 │   │   response.raise_for_status()                                                        │
│    62 │   │   # TODO: Optimise.                                                                  │
│    63 │   │   # https://github.com/openai/openai-python/blob/237448dc072a2c062698da3f9f512fae3   │
│    64 │   │   if not stream:                                                                     │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │            data = {                                                                          │ │
│ │                   │   'messages': [                                                          │ │
│ │                   │   │   {                                                                  │ │
│ │                   │   │   │   'role': 'user',                                                │ │
│ │                   │   │   │   'content': '###\nRole name: default\nYou are Command Line App  │ │
│ │                   ShellGPT, a programming and syst'+341                                      │ │
│ │                   │   │   }                                                                  │ │
│ │                   │   ],                                                                     │ │
│ │                   │   'model': 'gpt-3.5-turbo',                                              │ │
│ │                   │   'temperature': 0.1,                                                    │ │
│ │                   │   'top_p': 1.0,                                                          │ │
│ │                   │   'stream': True                                                         │ │
│ │                   }                                                                          │ │
│ │        endpoint = 'https://api.openai.com/v1/chat/completions'                               │ │
│ │        messages = [                                                                          │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': '###\nRole name: default\nYou are Command Line App      │ │
│ │                   ShellGPT, a programming and syst'+341                                      │ │
│ │                   │   }                                                                      │ │
│ │                   ]                                                                          │ │
│ │           model = 'gpt-3.5-turbo'                                                            │ │
│ │        response = <Response [429]>                                                           │ │
│ │            self = <sgpt.client.OpenAIClient object at 0x7fb864012e00>                        │ │
│ │          stream = True                                                                       │ │
│ │     temperature = 0.1                                                                        │ │
│ │ top_probability = 1.0                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/milesdredd/.local/lib/python3.10/site-packages/requests/models.py:1021 in raise_for_status │
│                                                                                                  │
│   1018 │   │   │   )                                                                             │
│   1019 │   │                                                                                     │
│   1020 │   │   if http_error_msg:                                                                │
│ ❱ 1021 │   │   │   raise HTTPError(http_error_msg, response=self)                                │
│   1022 │                                                                                         │
│   1023 │   def close(self):                                                                      │
│   1024 │   │   """Releases the connection back to the pool. Once this method has been            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ http_error_msg = '429 Client Error: Too Many Requests for url:                               │ │
│ │                  https://api.openai.com/v1/chat/comp'+7                                      │ │
│ │         reason = 'Too Many Requests'                                                         │ │
│ │           self = <Response [429]>                                                            │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/chat/completions`

**Comment by pmaoui** [comment]
Had the same issue, it's on OpenAI side and the reason is this one:
_In order to use the OpenAI API, you need to set up a paid account._
