### ISSUE TITLE
No way to change API key

### ISSUE THREAD

**Issue by antonsjoo** [TheR1D/shell_gpt#316]
I never got prompted for an api key and this is the error message i get prompted with:
Missing config key: OPENAI_API_KEY

Looked through the options in --help and nothing there either.

**Comment by harley84** [comment]
You can change the api key in runtime configuration file ~/.config/shell_gpt/.sgptrc:

**Comment by Drazulino** [comment]
but that file structure makes sense only for linux. Where in windows is the shell_gpt folder?
