### ISSUE TITLE
 Too Many Requests for url for simple prompt 

### ISSUE THREAD

**Issue by prakashcc** [TheR1D/shell_gpt#327]
While run the below command getting the error I tried with multiple key but same issues
  sgpt "nginx default config file location"
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/personal-pc/anaconda3/envs/shellgpt/lib/python3.11/site-packages/sgpt/app.py:167 in main   │
│                                                                                                  │
│   164 │   │   │   caching=cache,                                                                 │
│   165 │   │   )                                                                                  │
│   166 │   else:                                                                                  │
│ ❱ 167 │   │   full_completion = DefaultHandler(role_class).handle(                               │
│   168 │   │   │   prompt,                                                                        │
│   169 │   │   │   model=model,                                                                   │
│   170 │   │   │   temperature=temperature,                                                       │
│                                                                                                  │
│ ╭─────────────────────────────── locals ────────────────────────────────╮                        │
│ │               cache = True                                            │                        │
│ │                chat = None                                            │                        │
│ │                code = False                                           │                        │
│ │         create_role = None                                            │                        │
│ │      describe_shell = False                                           │                        │
│ │              editor = False                                           │                        │
│ │ install_integration = None                                            │                        │
│ │          list_chats = None                                            │                        │
│ │          list_roles = None                                            │                        │
│ │               model = 'gpt-3.5-turbo'                                 │                        │
│ │              prompt = 'nginx default config file location'            │                        │
│ │                repl = None                                            │                        │
│ │                role = None                                            │                        │
│ │          role_class = <sgpt.role.SystemRole object at 0x7f6587cc1e50> │                        │
│ │               shell = False                                           │                        │
│ │           show_chat = None                                            │                        │
│ │           show_role = None                                            │                        │
│ │        stdin_passed = False                                           │                        │
│ │         temperature = 0.1                                             │                        │
│ │     top_probability = 1.0                                             │                        │
│ ╰───────────────────────────────────────────────────────────────────────╯                        │
│                                                                                                  │
│ /home/personal-pc/anaconda3/envs/shellgpt/lib/python3.11/site-packages/sgpt/handlers/handler.py: │
│ 33 in handle                                                                                     │
│                                                                                                  │
│   30 │   │   stream = cfg.get("DISABLE_STREAMING") == "false"                                    │
│   31 │   │   if not stream:                                                                      │
│   32 │   │   │   typer.echo("Loading...\r", nl=False)                                            │
│ ❱ 33 │   │   for word in self.get_completion(messages=messages, **kwargs):                       │
│   34 │   │   │   typer.secho(word, fg=self.color, bold=True, nl=False)                           │
│   35 │   │   │   full_completion += word                                                         │
│   36 │   │   typer.echo("\033[K" if not stream else "")  # Overwrite "loading..."                │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ full_completion = ''                                                                         │ │
│ │          kwargs = {                                                                          │ │
│ │                   │   'model': 'gpt-3.5-turbo',                                              │ │
│ │                   │   'temperature': 0.1,                                                    │ │
│ │                   │   'top_probability': 1.0,                                                │ │
│ │                   │   'caching': True                                                        │ │
│ │                   }                                                                          │ │
│ │        messages = [                                                                          │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': '###\nRole name: default\nYou are Command Line App      │ │
│ │                   ShellGPT, a programming and syst'+351                                      │ │
│ │                   │   }                                                                      │ │
│ │                   ]                                                                          │ │
│ │          prompt = 'nginx default config file location'                                       │ │
│ │            self = <sgpt.handlers.default_handler.DefaultHandler object at 0x7f6587cb7710>    │ │
│ │          stream = True                                                                       │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/personal-pc/anaconda3/envs/shellgpt/lib/python3.11/site-packages/sgpt/handlers/handler.py: │
│ 25 in get_completion                                                                             │
│                                                                                                  │
│   22 │   │   raise NotImplementedError                                                           │
│   23 │                                                                                           │
│   24 │   def get_completion(self, **kwargs: Any) -> Generator[str, None, None]:                  │
│ ❱ 25 │   │   yield from self.client.get_completion(**kwargs)                                     │
│   26 │                                                                                           │
│   27 │   def handle(self, prompt: str, **kwargs: Any) -> str:                                    │
│   28 │   │   messages = self.make_messages(self.make_prompt(prompt))                             │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ kwargs = {                                                                                   │ │
│ │          │   'messages': [                                                                   │ │
│ │          │   │   {                                                                           │ │
│ │          │   │   │   'role': 'user',                                                         │ │
│ │          │   │   │   'content': '###\nRole name: default\nYou are Command Line App ShellGPT, │ │
│ │          a programming and syst'+351                                                         │ │
│ │          │   │   }                                                                           │ │
│ │          │   ],                                                                              │ │
│ │          │   'model': 'gpt-3.5-turbo',                                                       │ │
│ │          │   'temperature': 0.1,                                                             │ │
│ │          │   'top_probability': 1.0,                                                         │ │
│ │          │   'caching': True                                                                 │ │
│ │          }                                                                                   │ │
│ │   self = <sgpt.handlers.default_handler.DefaultHandler object at 0x7f6587cb7710>             │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/personal-pc/anaconda3/envs/shellgpt/lib/python3.11/site-packages/sgpt/client.py:98 in      │
│ get_completion                                                                                   │
│                                                                                                  │
│    95 │   │   :param caching: Boolean value to enable/disable caching.                           │
│    96 │   │   :return: String generated completion.                                              │
│    97 │   │   """                                                                                │
│ ❱  98 │   │   yield from self._request(                                                          │
│    99 │   │   │   messages,                                                                      │
│   100 │   │   │   model,                                                                         │
│   101 │   │   │   temperature,                                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │         caching = True                                                                       │ │
│ │        messages = [                                                                          │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': '###\nRole name: default\nYou are Command Line App      │ │
│ │                   ShellGPT, a programming and syst'+351                                      │ │
│ │                   │   }                                                                      │ │
│ │                   ]                                                                          │ │
│ │           model = 'gpt-3.5-turbo'                                                            │ │
│ │            self = <sgpt.client.OpenAIClient object at 0x7f6587cb7350>                        │ │
│ │     temperature = 0.1                                                                        │ │
│ │ top_probability = 1.0                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/personal-pc/anaconda3/envs/shellgpt/lib/python3.11/site-packages/sgpt/cache.py:39 in       │
│ wrapper                                                                                          │
│                                                                                                  │
│   36 │   │   │   │   yield cache_file.read_text()                                                │
│   37 │   │   │   │   return                                                                      │
│   38 │   │   │   result = ""                                                                     │
│ ❱ 39 │   │   │   for i in func(*args, **kwargs):                                                 │
│   40 │   │   │   │   result += i                                                                 │
│   41 │   │   │   │   yield i                                                                     │
│   42 │   │   │   cache_file.write_text(result)                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       args = (                                                                               │ │
│ │              │   <sgpt.client.OpenAIClient object at 0x7f6587cb7350>,                        │ │
│ │              │   [                                                                           │ │
│ │              │   │   {                                                                       │ │
│ │              │   │   │   'role': 'user',                                                     │ │
│ │              │   │   │   'content': '###\nRole name: default\nYou are Command Line App       │ │
│ │              ShellGPT, a programming and syst'+351                                           │ │
│ │              │   │   }                                                                       │ │
│ │              │   ],                                                                          │ │
│ │              │   'gpt-3.5-turbo',                                                            │ │
│ │              │   0.1,                                                                        │ │
│ │              │   1.0                                                                         │ │
│ │              )                                                                               │ │
│ │ cache_file = PosixPath('/tmp/cache/0b4d2c101948d88682cc60fc98bffbf1')                        │ │
│ │  cache_key = '0b4d2c101948d88682cc60fc98bffbf1'                                              │ │
│ │       func = <function OpenAIClient._request at 0x7f6587c768e0>                              │ │
│ │     kwargs = {}                                                                              │ │
│ │     result = ''                                                                              │ │
│ │       self = <sgpt.cache.Cache object at 0x7f65886c7350>                                     │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/personal-pc/anaconda3/envs/shellgpt/lib/python3.11/site-packages/sgpt/client.py:61 in      │
│ _request                                                                                         │
│                                                                                                  │
│    58 │   │   │   timeout=REQUEST_TIMEOUT,                                                       │
│    59 │   │   │   stream=stream,                                                                 │
│    60 │   │   )                                                                                  │
│ ❱  61 │   │   response.raise_for_status()                                                        │
│    62 │   │   # TODO: Optimise.                                                                  │
│    63 │   │   # https://github.com/openai/openai-python/blob/237448dc072a2c062698da3f9f512fae3   │
│    64 │   │   if not stream:                                                                     │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │            data = {                                                                          │ │
│ │                   │   'messages': [                                                          │ │
│ │                   │   │   {                                                                  │ │
│ │                   │   │   │   'role': 'user',                                                │ │
│ │                   │   │   │   'content': '###\nRole name: default\nYou are Command Line App  │ │
│ │                   ShellGPT, a programming and syst'+351                                      │ │
│ │                   │   │   }                                                                  │ │
│ │                   │   ],                                                                     │ │
│ │                   │   'model': 'gpt-3.5-turbo',                                              │ │
│ │                   │   'temperature': 0.1,                                                    │ │
│ │                   │   'top_p': 1.0,                                                          │ │
│ │                   │   'stream': True                                                         │ │
│ │                   }                                                                          │ │
│ │        endpoint = 'https://api.openai.com/v1/chat/completions'                               │ │
│ │        messages = [                                                                          │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': '###\nRole name: default\nYou are Command Line App      │ │
│ │                   ShellGPT, a programming and syst'+351                                      │ │
│ │                   │   }                                                                      │ │
│ │                   ]                                                                          │ │
│ │           model = 'gpt-3.5-turbo'                                                            │ │
│ │        response = <Response [429]>                                                           │ │
│ │            self = <sgpt.client.OpenAIClient object at 0x7f6587cb7350>                        │ │
│ │          stream = True                                                                       │ │
│ │     temperature = 0.1                                                                        │ │
│ │ top_probability = 1.0                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/personal-pc/anaconda3/envs/shellgpt/lib/python3.11/site-packages/requests/models.py:1021   │
│ in raise_for_status                                                                              │
│                                                                                                  │
│   1018 │   │   │   )                                                                             │
│   1019 │   │                                                                                     │
│   1020 │   │   if http_error_msg:                                                                │
│ ❱ 1021 │   │   │   raise HTTPError(http_error_msg, response=self)                                │
│   1022 │                                                                                         │
│   1023 │   def close(self):                                                                      │
│   1024 │   │   """Releases the connection back to the pool. Once this method has been            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ http_error_msg = '429 Client Error: Too Many Requests for url:                               │ │
│ │                  https://api.openai.com/v1/chat/comp'+7                                      │ │
│ │         reason = 'Too Many Requests'                                                         │ │
│ │           self = <Response [429]>                                                            │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/chat/completions

**Comment by 00-Python** [comment]
Check and see if you have exceeded your API usage hard limit: [OpenAI API Usage](https://platform.openai.com/account/usage) and if you have increase it [Increase Usage Limit](https://platform.openai.com/account/billing/limits). Once you have increased it, wait a min or so and try again.

**Comment by 7onn** [comment]
I have a similar problem and there's no way I trespassed this rate limit 🤔 I only used their API when I installed shell_gpt.

**Comment by KAGEYAM4** [comment]
It would be good if you include this in README.md. Even on openai website while creating api key it dosen't mention that a paid account i required now and there dashboard is just confusing.

https://stackoverflow.com/questions/75898276/openai-chatgpt-gpt-3-5-api-error-429-you-exceeded-your-current-quota-please

**Comment by dankraciun** [comment]
How I resolved my 429 error. 

1. The complimentary credit limit that is given to all users does not engage unless you add paid credits. 
2. After adding credits create a new API key
3. Update the key in your .bashrc file and update the variable in your venv
