### ISSUE TITLE
Feature request: add an option for --shell to execute immediately without prompting

### ISSUE THREAD

**Issue by davekirby** [TheR1D/shell_gpt#331]
I think sgpt is fantastic - keep up the great work.  

The one issue I have with it is that there is no way that I could find to suppress the --shell option from asking for permission to execute.   This means that you cannot pipe the output of the generated command to another process or redirect to a file. e.g.

`sgpt --shell "find all files in the directory tree less than 10 days old and print the first 20 lines" | less`

There should either be another option to execute without asking, or for the program to know when it is being piped to another process or file and not prompt (but I am not sure if that is possible on Windows).

Adding this would make sgpt even more great and open up a whole new world of uses.

I know I can work around this with the --code option, but it is a bit of a drag and probably won't work on Windows.  e.g.

`sgpt --code "write a bash command line to find all files in the directory tree less than 10 days old and print the first 20 lines" | bash | less`

**Comment by moritz-t-w** [comment]
#32
> Just a quick note, we have a [Discussions](https://github.com/TheR1D/shell_gpt/discussions) section on GitHub where we can discuss ideas, feature requests, and other topics related to this project.
>
> Using the [Discussions](https://github.com/TheR1D/shell_gpt/discussions) feature allows us to keep all conversations in one place, making it easier to keep track of feedback and ideas. Additionally, other community members can join in and provide feedback, leading to better collaboration and a more productive conversation.
>
> So, I encourage you to use the [Discussions](https://github.com/TheR1D/shell_gpt/discussions) feature for any ideas or feature requests you might have. This will help ensure that your ideas are seen and considered by the community, and we can work together to improve the project.

**Comment by TheR1D** [comment]
Closing this issue due to its age and lack of similar reports/requests from other users.
