### ISSUE TITLE
ZSH integration broken

### ISSUE THREAD

**Issue by syabro** [TheR1D/shell_gpt#332]
Looks like it doesn't a new line after the last command 
<img width="788" alt="image" src="https://github.com/TheR1D/shell_gpt/assets/29029/7702c1f6-675f-4766-acc6-851d24704021">

**Comment by xeruf** [comment]
Works for me :thinking:

**Comment by sorokine** [comment]
> Works for me 🤔

I think this works if your `~/.zshrc` has a new line at the end. It is safer to either add a check or simply add an empty line at the start of shell integration.
