### ISSUE TITLE
How to change default shortcut for shell integration

### ISSUE THREAD

**Issue by InstaJun** [TheR1D/shell_gpt#335]
The default shortcut for shell integration is ctr+l which has conflict with the keybinding of Terminator (clear the terminal). Is there any way to configure the shortcut for shell integration?

**Comment by DuyHuynhLe** [comment]
If you are using bash, look at the end of your ~/.bashrc , you will see the command 
`bind -x '"\C-l": _sgpt_bash'`

Change the shortcut Ctrl+l ("\C-l") to another combination, e.g. alt + l is "\el"

**Comment by InstaJun** [comment]
Thanks for your answer. I am now using zsh as my shell. At the end of my .zshrc file I have `_sgpt_zsh() {
if [[ -n "$BUFFER" ]]; then
    _sgpt_prev_cmd=$BUFFER
    BUFFER+="⌛"
    zle -I && zle redisplay
    BUFFER=$(sgpt --shell <<< "$_sgpt_prev_cmd")
    zle end-of-line
fi
}
zle -N _sgpt_zsh
bindkey ^l _sgpt_zsh`

After I change `bindkey ^l` to `bindkey ^i`, the shortcut of ctrl + i works. But I also recognize a phenomenon that the `tab` function under the Linux terminal seems to automatically trigger the function `_sgpt_zsh()`, which has the same effect as `Ctrl+i`. Is that normal?

**Comment by hugows** [comment]
https://unix.stackexchange.com/questions/563469/conflict-ctrl-i-with-tab-in-normal-mode#:~:text=Ctrl%2Bi%20and%20Tab%20are,corresponds%20to%20%22horizontal%20tab%22.

**Comment by InstaJun** [comment]
hi @hugows 
Thank you very much for your explanation! This is pretty helpful!

**Comment by aramacs** [comment]
Hey guys, I'm facing the same behavior. The bind key is somehow not working. When I get installed and source my zshrc I got this error. 

![image](https://github.com/TheR1D/shell_gpt/assets/69637662/9fb429d0-6f7c-41d7-8bd2-c502c151dee8)


When I put the keybind around '' the error goes out.
