### ISSUE TITLE
[Feature Request] Support InternLM

### ISSUE THREAD

**Issue by vansinhu** [TheR1D/shell_gpt#338]
Dear shell_gpt developer,

Greetings! I am vansinhu, a community developer and volunteer at InternLM. Your work has been immensely beneficial to me, and I believe it can be effectively utilized in InternLM as well. Welcome to add Discord https://discord.gg/gF9ezcmtM3 . I hope to get in touch with you.

Best regards,
vansinhu

**Comment by moritz-t-w** [comment]
#32
> Just a quick note, we have a [Discussions](https://github.com/TheR1D/shell_gpt/discussions) section on GitHub where we can discuss ideas, feature requests, and other topics related to this project.

> Using the [Discussions](https://github.com/TheR1D/shell_gpt/discussions) feature allows us to keep all conversations in one place, making it easier to keep track of feedback and ideas. Additionally, other community members can join in and provide feedback, leading to better collaboration and a more productive conversation.

> So, I encourage you to use the [Discussions](https://github.com/TheR1D/shell_gpt/discussions) feature for any ideas or feature requests you might have. This will help ensure that your ideas are seen and considered by the community, and we can work together to improve the project.
