### ISSUE TITLE
Resolving path extension

### ISSUE THREAD

**Issue by kid-gorgeous** [TheR1D/shell_gpt#34]
Hello, 

I've updated and installed Shell_GPT, imported my api key, and ran tests just to make sure that OpenAI establishes a connection. But unfortunately I run into a problem when I restart my terminal. It requires my to export my path each time using the command 

```export "/Users/<user>/Library/Python/3.11/bin/:$PATH"```

I was hoping to resolve the path issues so that I didn't have to restore it each time.

**Comment by TheR1D** [comment]
You can add a path in shell runtime configuration file. If you are using bash or zsh, try:
```
echo "PATH=$PATH:/Users/<user>/Library/Python/3.11/bin/" >> "$HOME/.$(basename $SHELL)rc"
```

**Comment by kid-gorgeous** [comment]
Awesome, this fixed it right up! Thanks!
