### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by levid0s** [TheR1D/shell_gpt#341]
Add `requirements.txt` for easy dependency install when running from source:

```
typer
distro
requests
rich
```

**Comment by johnnyaug** [comment]
To install dependencies for development you can run:
```
pip install -e ."[dev,test]"
```
as described in [CONTRIBUITNG.md](https://github.com/TheR1D/shell_gpt/blob/main/CONTRIBUITNG.md).

**Comment by TheR1D** [comment]
ShellGPT utilize `pyproject.toml` in order to pin dependecies. Closing this issue due to its age and lack of similar reports/requests from other users.
