### ISSUE TITLE
please go ahead and laugh

### ISSUE THREAD

**Issue by careyjames** [TheR1D/shell_gpt#347]
where is the correct place to change the repl prompt?
i like the unicorn idea.

**Comment by hcal** [comment]
For most Linux distributions the default shell is bash.  If you are using one of those, you can set the prompt to almost anything you want in .bashrc.  


Just find the existing 'PS1=' line and change it to  `PS1='🦄'`,  If it doesn't exist, add it to the bottom of the file.  


I set mine to cycle through the phases of the moon.

 
```
# Declare an index and the array of moon phases
moon_index=0
moon_phases=("🌕" "🌖" "🌗" "🌘" "🌑" "🌒" "🌓" "🌔")

# Function to update the moon phase
update_moon_phase () {
  moon=${moon_phases[moon_index]}
  let "moon_index = (moon_index + 1) % 8"
}

# Update the moon phase before each command
PROMPT_COMMAND=update_moon_phase

# Include the moon variable in your PS1
#PS1=' ${moon} [\W] \$ '
PS1='[\W] ${moon} '

```

If you are using Mac, I think it uses zsh,  You can search for setting shell prompt on zsh.  I think it is pretty similar - possibly the same -, but I dont use zshell so I'm not certain.

**Comment by careyjames** [comment]
thank you! that is cool!
