### ISSUE TITLE
[BUG] JSONDecodeError: Unterminated string starting at: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by espin086** [TheR1D/shell_gpt#353]
After every prompt I am getting an error now, the code completion finishes. but then I get this JSONDecodeError: 

**Example Prompt:** 

`sgpt "create a path release that cleaned up the backend code, speficially introduced a class that handles all of the file transfers. Give me nice Github worth release notes with emojis"`

**Error:** 

🎉 New Release: v1.0.0 🎉

🔧 Backend Code Cleanup and File Transfer Class Introduction 🔧

📦 Features:
- Implemented a new class, `FileTransferHandler`, to handle all file transfers efficiently. 📂🔗
- Streamlined the backend code for improved performance and maintainability. 💪🔨
- Optimized file transfer operations for faster and more reliable transfers. ⚡️💾

🐛 Bug Fixes:
- Resolved various issues related to file transfer failures and inconsistencies. 🐞🔧
- Fixed a bug causing occasional crashes during file transfers. 🚫🔌

📖 Documentation:
- Updated the documentation to include detailed instructions on using the `FileTransferHandler` class. 📚📝
- Added examples and code snippets to help developers quickly integrate file transfer functionality. 💡💻

🚀 Other Improvements:
- Enhanced error handling and error messages for better troubleshooting. 🛠️❗
- Improved overall stability and performance of the application. 💯✨

🔗 Check out the full release on GitHub: [Release v1.0.0](https://github.com/your-```
repo/releases/tag/v1.0.0)╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/jjespinoza/Library/Python/3.9/lib/python/site-packages/sgpt/app.py:167 in main            │
│                                                                                                  │
│   164 │   │   │   caching=cache,                                                                 │
│   165 │   │   )                                                                                  │
│   166 │   else:                                                                                  │
│ ❱ 167 │   │   full_completion = DefaultHandler(role_class).handle(                               │
│   168 │   │   │   prompt,                                                                        │
│   169 │   │   │   model=model,                                                                   │
│   170 │   │   │   temperature=temperature,                                                       │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │               cache = True                                                                   │ │
│ │                chat = None                                                                   │ │
│ │                code = False                                                                  │ │
│ │         create_role = None                                                                   │ │
│ │      describe_shell = False                                                                  │ │
│ │              editor = False                                                                  │ │
│ │ install_integration = None                                                                   │ │
│ │          list_chats = None                                                                   │ │
│ │          list_roles = None                                                                   │ │
│ │               model = 'gpt-3.5-turbo'                                                        │ │
│ │              prompt = 'create a path release that cleaned up the backend code, speficially   │ │
│ │                       introduced a'+98                                                       │ │
│ │                repl = None                                                                   │ │
│ │                role = None                                                                   │ │
│ │          role_class = <sgpt.role.SystemRole object at 0x100ce5a60>                           │ │
│ │               shell = False                                                                  │ │
│ │           show_chat = None                                                                   │ │
│ │           show_role = None                                                                   │ │
│ │        stdin_passed = False                                                                  │ │
│ │         temperature = 0.1                                                                    │ │
│ │     top_probability = 1.0                                                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/jjespinoza/Library/Python/3.9/lib/python/site-packages/sgpt/handlers/handler.py:33 in     │
│ handle                                                                                           │
│                                                                                                  │
│   30 │   │   stream = cfg.get("DISABLE_STREAMING") == "false"                                    │
│   31 │   │   if not stream:                                                                      │
│   32 │   │   │   typer.echo("Loading...\r", nl=False)                                            │
│ ❱ 33 │   │   for word in self.get_completion(messages=messages, **kwargs):                       │
│   34 │   │   │   typer.secho(word, fg=self.color, bold=True, nl=False)                           │
│   35 │   │   │   full_completion += word                                                         │
│   36 │   │   typer.echo("\033[K" if not stream else "")  # Overwrite "loading..."                │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ full_completion = '🎉 New Release: v1.0.0 🎉\n\n🔧 Backend Code Cleanup and File Transfer    │ │
│ │                   Class Introduc'+945                                                        │ │
│ │          kwargs = {                                                                          │ │
│ │                   │   'model': 'gpt-3.5-turbo',                                              │ │
│ │                   │   'temperature': 0.1,                                                    │ │
│ │                   │   'top_probability': 1.0,                                                │ │
│ │                   │   'caching': True                                                        │ │
│ │                   }                                                                          │ │
│ │        messages = [                                                                          │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': '###\nRole name: default\nYou are Command Line App      │ │
│ │                   ShellGPT, a programming and syst'+490                                      │ │
│ │                   │   }                                                                      │ │
│ │                   ]                                                                          │ │
│ │          prompt = 'create a path release that cleaned up the backend code, speficially       │ │
│ │                   introduced a'+98                                                           │ │
│ │            self = <sgpt.handlers.default_handler.DefaultHandler object at 0x100ce5070>       │ │
│ │          stream = True                                                                       │ │
│ │            word = ')'                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/jjespinoza/Library/Python/3.9/lib/python/site-packages/sgpt/handlers/handler.py:25 in     │
│ get_completion                                                                                   │
│                                                                                                  │
│   22 │   │   raise NotImplementedError                                                           │
│   23 │                                                                                           │
│   24 │   def get_completion(self, **kwargs: Any) -> Generator[str, None, None]:                  │
│ ❱ 25 │   │   yield from self.client.get_completion(**kwargs)                                     │
│   26 │                                                                                           │
│   27 │   def handle(self, prompt: str, **kwargs: Any) -> str:                                    │
│   28 │   │   messages = self.make_messages(self.make_prompt(prompt))                             │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ kwargs = {                                                                                   │ │
│ │          │   'messages': [                                                                   │ │
│ │          │   │   {                                                                           │ │
│ │          │   │   │   'role': 'user',                                                         │ │
│ │          │   │   │   'content': '###\nRole name: default\nYou are Command Line App ShellGPT, │ │
│ │          a programming and syst'+490                                                         │ │
│ │          │   │   }                                                                           │ │
│ │          │   ],                                                                              │ │
│ │          │   'model': 'gpt-3.5-turbo',                                                       │ │
│ │          │   'temperature': 0.1,                                                             │ │
│ │          │   'top_probability': 1.0,                                                         │ │
│ │          │   'caching': True                                                                 │ │
│ │          }                                                                                   │ │
│ │   self = <sgpt.handlers.default_handler.DefaultHandler object at 0x100ce5070>                │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/jjespinoza/Library/Python/3.9/lib/python/site-packages/sgpt/client.py:98 in               │
│ get_completion                                                                                   │
│                                                                                                  │
│    95 │   │   :param caching: Boolean value to enable/disable caching.                           │
│    96 │   │   :return: String generated completion.                                              │
│    97 │   │   """                                                                                │
│ ❱  98 │   │   yield from self._request(                                                          │
│    99 │   │   │   messages,                                                                      │
│   100 │   │   │   model,                                                                         │
│   101 │   │   │   temperature,                                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │         caching = True                                                                       │ │
│ │        messages = [                                                                          │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': '###\nRole name: default\nYou are Command Line App      │ │
│ │                   ShellGPT, a programming and syst'+490                                      │ │
│ │                   │   }                                                                      │ │
│ │                   ]                                                                          │ │
│ │           model = 'gpt-3.5-turbo'                                                            │ │
│ │            self = <sgpt.client.OpenAIClient object at 0x1022437f0>                           │ │
│ │     temperature = 0.1                                                                        │ │
│ │ top_probability = 1.0                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/jjespinoza/Library/Python/3.9/lib/python/site-packages/sgpt/cache.py:39 in wrapper        │
│                                                                                                  │
│   36 │   │   │   │   yield cache_file.read_text()                                                │
│   37 │   │   │   │   return                                                                      │
│   38 │   │   │   result = ""                                                                     │
│ ❱ 39 │   │   │   for i in func(*args, **kwargs):                                                 │
│   40 │   │   │   │   result += i                                                                 │
│   41 │   │   │   │   yield i                                                                     │
│   42 │   │   │   cache_file.write_text(result)                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       args = (                                                                               │ │
│ │              │   <sgpt.client.OpenAIClient object at 0x1022437f0>,                           │ │
│ │              │   [                                                                           │ │
│ │              │   │   {                                                                       │ │
│ │              │   │   │   'role': 'user',                                                     │ │
│ │              │   │   │   'content': '###\nRole name: default\nYou are Command Line App       │ │
│ │              ShellGPT, a programming and syst'+490                                           │ │
│ │              │   │   }                                                                       │ │
│ │              │   ],                                                                          │ │
│ │              │   'gpt-3.5-turbo',                                                            │ │
│ │              │   0.1,                                                                        │ │
│ │              │   1.0                                                                         │ │
│ │              )                                                                               │ │
│ │ cache_file = PosixPath('/var/folders/bn/gpsh1csx5cn3n2b260wncbvm0000gn/T/cache/6ada852fe882… │ │
│ │  cache_key = '6ada852fe882a51afb5e478dc3b1d1a4'                                              │ │
│ │       func = <function OpenAIClient._request at 0x10225dd30>                                 │ │
│ │          i = ')'                                                                             │ │
│ │     kwargs = {}                                                                              │ │
│ │     result = '🎉 New Release: v1.0.0 🎉\n\n🔧 Backend Code Cleanup and File Transfer Class   │ │
│ │              Introduc'+945                                                                   │ │
│ │       self = <sgpt.cache.Cache object at 0x101b0b760>                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/jjespinoza/Library/Python/3.9/lib/python/site-packages/sgpt/client.py:74 in _request      │
│                                                                                                  │
│    71 │   │   │   │   break                                                                      │
│    72 │   │   │   if not data:                                                                   │
│    73 │   │   │   │   continue                                                                   │
│ ❱  74 │   │   │   data = json.loads(data)  # type: ignore                                        │
│    75 │   │   │   delta = data["choices"][0]["delta"]  # type: ignore                            │
│    76 │   │   │   if "content" not in delta:                                                     │
│    77 │   │   │   │   continue                                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │            data = '"{\\"rate_limit_usage\\": {\\'                                            │ │
│ │           delta = {}                                                                         │ │
│ │        endpoint = 'https://api.openai.com/v1/chat/completions'                               │ │
│ │            line = b'data: "{\\"rate_limit_usage\\": {\\'                                     │ │
│ │        messages = [                                                                          │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': '###\nRole name: default\nYou are Command Line App      │ │
│ │                   ShellGPT, a programming and syst'+490                                      │ │
│ │                   │   }                                                                      │ │
│ │                   ]                                                                          │ │
│ │           model = 'gpt-3.5-turbo'                                                            │ │
│ │        response = <Response [200]>                                                           │ │
│ │            self = <sgpt.client.OpenAIClient object at 0x1022437f0>                           │ │
│ │          stream = True                                                                       │ │
│ │     temperature = 0.1                                                                        │ │
│ │ top_probability = 1.0                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python │
│ 3.9/json/__init__.py:346 in loads                                                                │
│                                                                                                  │
│   343 │   if (cls is None and object_hook is None and                                            │
│   344 │   │   │   parse_int is None and parse_float is None and                                  │
│   345 │   │   │   parse_constant is None and object_pairs_hook is None and not kw):              │
│ ❱ 346 │   │   return _default_decoder.decode(s)                                                  │
│   347 │   if cls is None:                                                                        │
│   348 │   │   cls = JSONDecoder                                                                  │
│   349 │   if object_hook is not None:                                                            │
│                                                                                                  │
│ ╭────────────────────── locals ───────────────────────╮                                          │
│ │               cls = None                            │                                          │
│ │                kw = {}                              │                                          │
│ │       object_hook = None                            │                                          │
│ │ object_pairs_hook = None                            │                                          │
│ │    parse_constant = None                            │                                          │
│ │       parse_float = None                            │                                          │
│ │         parse_int = None                            │                                          │
│ │                 s = '"{\\"rate_limit_usage\\": {\\' │                                          │
│ ╰─────────────────────────────────────────────────────╯                                          │
│                                                                                                  │
│ /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python │
│ 3.9/json/decoder.py:337 in decode                                                                │
│                                                                                                  │
│   334 │   │   containing a JSON document).                                                       │
│   335 │   │                                                                                      │
│   336 │   │   """                                                                                │
│ ❱ 337 │   │   obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                  │
│   338 │   │   end = _w(s, end).end()                                                             │
│   339 │   │   if end != len(s):                                                                  │
│   340 │   │   │   raise JSONDecodeError("Extra data", s, end)                                    │
│                                                                                                  │
│ ╭────────────────────────────── locals ──────────────────────────────╮                           │
│ │   _w = <built-in method match of re.Pattern object at 0x1019e46f0> │                           │
│ │    s = '"{\\"rate_limit_usage\\": {\\'                             │                           │
│ │ self = <json.decoder.JSONDecoder object at 0x101a96490>            │                           │
│ ╰────────────────────────────────────────────────────────────────────╯                           │
│                                                                                                  │
│ /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python │
│ 3.9/json/decoder.py:353 in raw_decode                                                            │
│                                                                                                  │
│   350 │   │                                                                                      │
│   351 │   │   """                                                                                │
│   352 │   │   try:                                                                               │
│ ❱ 353 │   │   │   obj, end = self.scan_once(s, idx)                                              │
│   354 │   │   except StopIteration as err:                                                       │
│   355 │   │   │   raise JSONDecodeError("Expecting value", s, err.value) from None               │
│   356 │   │   return obj, end                                                                    │
│                                                                                                  │
│ ╭──────────────────────── locals ─────────────────────────╮                                      │
│ │  idx = 0                                                │                                      │
│ │    s = '"{\\"rate_limit_usage\\": {\\'                  │                                      │
│ │ self = <json.decoder.JSONDecoder object at 0x101a96490> │                                      │
│ ╰─────────────────────────────────────────────────────────╯                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
JSONDecodeError: Unterminated string starting at: line 1 column 1 (char 0)
```

**Comment by Adjenz** [comment]
Same error here.

**Comment by espin086** [comment]
Not happening anymore

**Comment by Adjenz** [comment]
Yep, same here.
