### ISSUE TITLE
Not working - 401

### ISSUE THREAD

**Issue by alexanderzeillinger** [TheR1D/shell_gpt#357]
I have entered a valid key in .sgptrc but it doesn't work:

![image](https://github.com/TheR1D/shell_gpt/assets/126621/bf6e12cc-f58a-4dfa-a473-26998e502c55)

**Comment by ezeike** [comment]
![image](https://github.com/TheR1D/shell_gpt/assets/12902351/d82087e9-6a76-48a4-97a7-a6d44b5ea3de)

**Comment by ezeike** [comment]
It was working fine one day, then not the next. It started working again without me changing anything. I guess it was on OpenAI's end.

**Comment by moritz-t-w** [comment]
OpenAI has been spilling coffee on their servers a lot recently. Whenever these happen, just report it on https://downdetector.com/status/openai/ and wait for a while ¯\\\_(ツ)_/¯

**Comment by TheR1D** [comment]
This issue is related to OpenAI API.

**Comment by alexanderzeillinger** [comment]
So 1 year later I tried again, still same error - quite a coincidence that this is again caused by OpenAI API.

**Comment by moritz-t-w** [comment]
yes. A coincidence
