### ISSUE TITLE
slow repsonse time

### ISSUE THREAD

**Issue by doebi** [TheR1D/shell_gpt#361]
Anyone else experiencing very slow respones from ChatGPT?

It's like the responses come in byte by byte similar to DSL times. Very annoying, when you are busy..

**Comment by mountaineerbr** [comment]
Indeed, sometimes, yes. Try changing the model, for example, instead of `gpt-3.5-turbo-0613`, or `gpt-3.5-turbo`, try `gpt-3.5-turbo-0301`.
For `gpt-4`, you may try `gpt-4-0314`.

**Comment by doebi** [comment]
Thanks, for your input.

I moved to `gpt-4-1106-preview` after the latest announcement.
It is significantly faster than before.
