### ISSUE TITLE
[Feature Request]Speech-to-text input

### ISSUE THREAD

**Issue by petric3** [TheR1D/shell_gpt#363]
Thank you for the awesome package!!
I have a humble request to add speech-to-text input option. Can imagine it could not be so easy to add, but it's very useful,  I use it a lot on android chatGPT app.

**Comment by mountaineerbr** [comment]
While this is not implemented here, you may want to try my `chatgpt.sh` shell script which supports it.
Try running the chat cmpls mode together with `option -w` (whisper-in), such as: **`chatgpt.sh -cc -w en`**
This will record the microphone with sox, or other recording programme, transcribe to english and submit to gpt-3.5. Cheers!

**Comment by gwpl** [comment]
Maybe helpful piece of python code:

* https://twitter.com/GWierzowiecki/status/1723732796617679130  =>  https://github.com/CLIAI/handy_scripts/blob/main/openai_stt_cli.py

**Comment by TheR1D** [comment]
I don't think such feature will be added into ShellGPT. I think it is possible to use some other tools to convert speech to text and just pipe it into `sgpt`.
