### ISSUE TITLE
Odd shell role behavior when using GPT-4-Turbo

### ISSUE THREAD

**Issue by terberlo** [TheR1D/shell_gpt#368]
Things work normally with gpt-3.5-turbo, but when I try the newly released gpt-4-turbo I'm getting an odd prepend/postpend to my shell commands:  

```
root@nas:~/.config/shell_gpt# sgpt --model gpt-3.5-turbo -s "print working directory"
pwd
[E]xecute, [D]escribe, [A]bort: e
/root/.config/shell_gpt
root@nas:~/.config/shell_gpt#
```

=-=-=-
versus
=-=-=-

```
root@nas:~/.config/shell_gpt# sgpt --model gpt-4-1106-preview -s "print working directory"
```bash
pwd
_```
[E]xecute, [D]escribe, [A]bort: e
root@nas:~/.config/shell_gpt# exit
exit
/bin/bash: line 3: /root/.config/shell_gpt: Is a directory
root@nas:~/.config/shell_gpt#
```

**Comment by yorgaraz** [comment]
I copied the \nIMPORTANT: Provide only plain text without Markdown formatting.\nIMPORTANT: Do not include markdown formatting such as ```.
from ~/.config/shell_gpt/roles/code.json into ~/.config/shell_gpt/roles/shell.json and gpt4 turbo now appears to respect the no md rule.

**Comment by David-Else** [comment]
I added something similar to fix this new problem, `Do not wrap in a markdown block`:
```sh
"role": "Provide only bash commands for Linux/Debian GNU/Linux 12 (bookworm) without any description.\nIf there is a lack of details, provide most logical solution.\nDo not wrap in a markdown block \nEnsure the output is a valid shell command.\nIf multiple steps required try to combine them together."
```
It does not seem to need the `IMPORTANT:`. A pull request needs to be made for one of these solutions.

**Comment by darvein** [comment]
Humm, I'm getting a different response:
```Invalid value for '--model': 'gpt-4-1106-preview' is not one of 'gpt-3.5-turbo', 'gpt-4', 'gpt-4-32k'.```

**Comment by David-Else** [comment]
@darvein Try `alias ai="sgpt --model='gpt-4-1106-preview'"`

**Comment by gwpl** [comment]
Maybe instead of forcing model to not do Markdown formatting, better to use function calling convention?
https://platform.openai.com/docs/guides/function-calling

Otherwise, maybe also worth making "code extractor" i.e. in case there is 

``````
Text

```
codeblock
```

test
``````

in case there is one codeblock in given returned response, to extract this codeblock?
