### ISSUE TITLE
`--chat-file-as-path` Flag and Environment Variable for Local Chat File Management [Feature Request]

### ISSUE THREAD

**Issue by gwpl** [TheR1D/shell_gpt#371]
**Request for Changes or Improvements:**
* [ ] Implement a new flag `--chat-file-as-path` that changes behavious so now chats (instead of being pointed to temporary directory) now chat names will be treated as path to file storing chat json file.
* [ ] Create an environment variable `THER1D_SGPT_CHAT_AS_FILE` that can be set to `true` to enable the new behavior by default (of false).
* [ ] `jq` style of formatting, so to enable readable  `diff` or `git diff` or manually modifying chat conversation file.

**Additional Context:**
* The proposed feature would significantly reduce the manual effort currently required to manage chat files and integrate them with version control systems.
* By allowing direct specification of the chat file path and ensuring a version control-friendly format, users can more easily maintain and review their chat histories.

**Current workaround:**
Current workaround require:
* manual creation of json file
* going to temporary directory where sgpt keeps chats
* making that symbolic link to desired file

**Comment by gwpl** [comment]
One another opportunity how keeping json files, could turn helpful!

ChatGPT deprecated feature to "continue conversatin", so now we can have conversations using shell_gpt and share files:

![Screenshot_20231117_111618](https://github.com/TheR1D/shell_gpt/assets/221403/71fa2e85-270a-4025-a6c6-80ade36b67fe)

> ⚠️ The option to continue a conversation from a shared link has been deprecated for users across all plans in ChatGPT.

https://help.openai.com/en/articles/7925741-chatgpt-shared-links-faq

**Comment by TheR1D** [comment]
Chat files folder is configurable in config file `~/.config/shell_gpt/.sgptrc`.
Closing this issue due to its age and lack of similar reports/requests from other users.
