### ISSUE TITLE
Pipe "Rile: xxx" and similar thing into standard error stream?

### ISSUE THREAD

**Issue by gwpl** [TheR1D/shell_gpt#372]
Could you please consider printing meta information like `Role: xxx ` into stdnard error stream, so one can pipe : `cat a | sgpt '....' | tee b` ?

(of at least to make it via flag `--meta-on-stderr`  or disable via flag e.g. `--silent` ?)

**Comment by TheR1D** [comment]
Closing this issue due to its age and lack of similar reports/requests from other users.
