### ISSUE TITLE
"Command Not Found" after installation

### ISSUE THREAD

**Issue by danteswrath** [TheR1D/shell_gpt#373]
Installed shell-gpt, was prompt for the API key, it worked once, but after that it says "command not found."  I was watching a video that suggested going into ~/.bashrc to export PATH=$PATH:~/.local/bin:/usr/bin/python and after that shell-gpt stopped working.  I removed the export from the bashrc file and it still won't work

**Comment by TheR1D** [comment]
Closing this issue due to its age and lack of similar reports/requests from other users.
