### ISSUE TITLE
syntax highlighting code output in REPL

### ISSUE THREAD

**Issue by berntxspeed** [TheR1D/shell_gpt#374]
Hey just wanted to submit a additional readme item that users might appreciate.  

I managed to pipe the REPL into the "bat" command
https://github.com/sharkdp/bat
and can still use the REPL iteratively but have syntax highlighting of the outputted code from sgpt.  

>sgpt --code --repl temp | bat -l scala --paging=never

ref this part of the "bat" readme: 
https://github.com/sharkdp/bat#tail--f

Cheers!

**Comment by TheR1D** [comment]
https://github.com/TheR1D/shell_gpt/discussions/200
