### ISSUE TITLE
Separate cache by user for multi-user systems [Request] to fix [Bug][Crash]

### ISSUE THREAD

**Issue by gwpl** [TheR1D/shell_gpt#379]
```bash
[user@machine]$ echo testXY|sgpt --no-cache 'testXY'
(...)
PermissionError: [Errno 13] Permission denied: '/tmp/cache/98b75d8471ca0fcdc8ec49686f118ba0'
```

Proposal:

* `/tmp/cache-${UID}/...` 

(also, why do I have cache error even I use "--no-cache" flag in this case for debugging?

Anyway, spearate cache by user makes sense for multi-user systems.

Also ability to change cache directory via ENVIRONMENT variable (e.g. `TheR1D_SGPT_CACHE_DIR` would be great! I would love to have persistence across reboots in some cases!)

**Comment by gwpl** [comment]
Clearly that is the problem, after this:

```
chmod uog+rwx /tmp/cache
```

as test, different users can use sgpt, as long as there is no collision on cache...

anyway, pattern seems wrong and cache directories should be separate for different users on multi user operating systems, e.g. :

```
/tmp/cache-${UID}/
```

**Comment by TheR1D** [comment]
I think users can define different cache folders using their config files `~/.config/shell_gpt/.sgptrc` in order to avoid overwriting and potentially other issues.
