### ISSUE TITLE
Prompt Issue

### ISSUE THREAD

**Issue by DenyZeka** [TheR1D/shell_gpt#39]
Is it possible to change the initial prompt (if there is an initial prompt)? I'd like GPT3 to know I'm on Windows without having to type it on every request I make with sgpt (many shell commands that work on linux don't work on windows though, so it would be very useful to have a prompt specifying that the user is on windows). Obviously it's not just for this, a starting prompt that needs to be set only once could be used for many other uses could be very convenient and comfy for me

**Comment by TheR1D** [comment]
I see, when I was making this tool I was expecting Unix-based systems as main platform. Therefore, now it always outputs shell commands for `--shell`. I will have a look how we can adapt it to query PowerShell commands based on the OS, and probably will include a solution in coming patch.

**Comment by TheR1D** [comment]
I just pushed new patch with PowerShell support (for `--shell` argument), upgrade your version of `sgpt` using `pip install shell-gpt --upgrade` and try it on Windows.
