### ISSUE TITLE
Problems with `--shell` | `-s`

### ISSUE THREAD

**Issue by gwpl** [TheR1D/shell_gpt#397]
pressing "E" , does not execute, instead I am inside my custom prompt of my shell.

my suspect is that `os.system(...)` is too simple, as taking contactenated , string and probably we should use something like:

```
import subprocess
subprocess.call(['command', 'arg1', 'arg2'])
```

Potentially related bugs:

* #332
* #368
* #278

**Comment by TheR1D** [comment]
Closing this issue due to its age and the absence of similar reports.
