### ISSUE TITLE
TypeError when used with xusenlinzy/api-for-open-llm

### ISSUE THREAD

**Issue by pengtb** [TheR1D/shell_gpt#411]
[xusenlinzy/api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm) is another backend similar to LocalAI that can provide OpenAI-like API for local LLMs. However it is wierd that its generated completions end with a `None`, then shell_gpt would show a TypeError.
![image](https://github.com/TheR1D/shell_gpt/assets/39072131/e717aa4b-edf1-41fe-9302-4eec59c54ab5)
Maybe better to add type checks before concatenating?
Places are:
- sgpt/cache.py:40
- sgpt/handlers/handler.py:37

**Comment by timcrowell** [comment]
I'm seeing the exact same thing when using [BerriAI/litellm](https://github.com/BerriAI/litellm) as the backend.  Litellm would be particularly useful in combination with shell_gpt because it would allow switching between a local model and OpenAI using just the --model switch.

**Comment by TheR1D** [comment]
I didn't test `sgpt` with any other backends except OpenAI and LocalAI, but as I can see the error you are getting is related to cache. Try to disable caching `sgpt --no-cache "test"`.

**Comment by TheR1D** [comment]
ShellGPT with [LiteLLM](https://github.com/BerriAI/litellm) was released as 1.3.0. This should fix the issue, given that I'm closing this issue, but feel free to reopen it.
