### ISSUE TITLE
 '404 Client Error: Not Found for url:  https://api.openai.com/v1/chat/completions' with gpt-4-32k-0613 model

### ISSUE THREAD

**Issue by dmikushin** [TheR1D/shell_gpt#420]
While the default model `gpt-4-1106-preview` works normally, I get the following error when trying to use `gpt-4-32k-0613` model:

```
404 Client Error: Not Found for url:  https://api.openai.com/v1/chat/completions
```
What could be the issue here?

**Comment by rounak3** [comment]
mine is also having this same issue did you founad a fix for that

**Comment by TheR1D** [comment]
You need to have paid account in order to user `gpt-4` more details [here](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4). You might be able to use `gpt-3.5-turbo` model with free account:
```shell
sgpt --model gpt-3.5-turbo "test"
```

**Comment by dmikushin** [comment]
Hi @TheR1D , no for me the problem is with a paid account.

**Comment by rounak3** [comment]
Hii @TheR1D  yeah i also tried that it's giving me another error (HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/chat/completions
)

**Comment by JamesRivers** [comment]
same for me - DEFAULT_MODEL=gpt-4-1106-preview

**Comment by mrcnski** [comment]
I tried `gpt-3.5-turbo` but no cigar:

```
HTTPError: 404 Client Error: Not Found for url: https://api.openai.com/v1/chat/completions
```

At least shellgpt has beautiful error messages!

**Comment by dmikushin** [comment]
@TheR1D , it feels that we all have different permissions to access different models. I do have access to gpt-4, but not to the gpt-4-32k. No idea why, perhaps OpenAI has different access levels even for the paid accounts. What shell_gpt could do to address this issue is to display the full https://api.openai.com/v1/chat/completions response that explains the actual reason of error to everyone.

**Comment by haydenjames** [comment]
Same issue here:
`HTTPError: 404 Client Error: Not Found for url: https://api.openai.com/v1/chat/completions`

**Comment by Petfrogg** [comment]
The default:
gpt-4-1106-preview = error 404
gpt-3.5-turbo = error

**Comment by TheR1D** [comment]
In the [latest release](https://github.com/TheR1D/shell_gpt/releases/tag/1.1.0) these error will come with description and possible solutions. Run `pip install shell-gpt --upgrade` to install latest version.

**Comment by Petfrogg** [comment]
Same problem after upgrade

**Comment by dmikushin** [comment]
I've solved this for myself by switching from OpenAI to OpenRouter.

That is, I register an OpenRouter account and adjust `~/.config/shell_gpt/.sgptrc` accordingly:

```
OPENAI_API_HOST=https://api.openrouter.ai
OPENAI_API_KEY=<your_open_router_key_here>
OPENAI_BASE_URL=https://openrouter.ai/api/v1
```

I also make sure that the "default model" in OpenRouter settings is `gpt4-32k`:

![Screenshot from 2024-01-11 12-23-29](https://github.com/TheR1D/shell_gpt/assets/5672874/b5bc41c8-914a-4fa0-98d5-a212873972c5)

And now I finally get the `gpt4-32k` working without an error!

So, the problem discussed here is all about OpenAI's inability to properly manage their users. OpenAI enables certain models for ones and disables for others, without any clear logic. OK then OpenRouter is a proxy, which works around it.

**Comment by jrbecart** [comment]
As mentioned (in other issues), If you have ChatGPT plus subscription you also need to buy credit here:
[https://platform.openai.com/account/billing/overview](https://platform.openai.com/account/billing/overview)

THEN wait few minutes!
