### ISSUE TITLE
HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/chat/completions

### ISSUE THREAD

**Issue by gagaltotal** [TheR1D/shell_gpt#424]
Server Ubuntu 22.04
sgpt --version : ShellGPT 1.0.1

python3 --version : Python 3.10.12

pip3 --version : pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

package pip : 
pip install shell-gpt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: shell-gpt in ./.local/lib/python3.10/site-packages (1.0.1)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/lib/python3/dist-packages (from shell-gpt) (8.0.3)
Requirement already satisfied: rich<14.0.0,>=13.1.0 in ./.local/lib/python3.10/site-packages (from shell-gpt) (13.7.0)
Requirement already satisfied: typer<1.0.0,>=0.7.0 in ./.local/lib/python3.10/site-packages (from shell-gpt) (0.9.0)
Requirement already satisfied: requests<3.0.0,>=2.28.2 in ./.local/lib/python3.10/site-packages (from shell-gpt) (2.31.0)
Requirement already satisfied: distro<2.0.0,>=1.8.0 in ./.local/lib/python3.10/site-packages (from shell-gpt) (1.9.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3.0.0,>=2.28.2->shell-gpt) (2020.6.20)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3.0.0,>=2.28.2->shell-gpt) (3.3)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.local/lib/python3.10/site-packages (from requests<3.0.0,>=2.28.2->shell-gpt) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests<3.0.0,>=2.28.2->shell-gpt) (1.26.5)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.local/lib/python3.10/site-packages (from rich<14.0.0,>=13.1.0->shell-gpt) (2.17.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.local/lib/python3.10/site-packages (from rich<14.0.0,>=13.1.0->shell-gpt) (3.0.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./.local/lib/python3.10/site-packages (from typer<1.0.0,>=0.7.0->shell-gpt) (4.9.0)
Requirement already satisfied: mdurl~=0.1 in ./.local/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=13.1.0->shell-gpt) (0.1.2)

setup API key default =  ~/.config/shell_gpt/.sgptrc = done..

why error HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/chat/completions ?

**Comment by TheR1D** [comment]
You probably using free tier account. Currently it is required to link credit/debit card in order to make API requests. https://github.com/TheR1D/shell_gpt/issues/201
