### ISSUE TITLE
Invalid OpenAI API Key

### ISSUE THREAD

**Issue by dkhodan** [TheR1D/shell_gpt#426]
sgpt --version: 1.0.1

Installation went OK. 
When I try to test it, it throws me an error:  "404 Client Error: Not Found for url:                  https://api.openai.com/v1/chat/completions" that referring API key is wrong. 

I did update API key already few times and double checked if it is set properly in configs. 

Additionally, on unwinded stack I'm actually able to see reply from model gpt-4-1106-preview.

**Comment by superterran** [comment]
I'm having the same issue

**Comment by TheR1D** [comment]
@dkhodan thank you for reporting this issue, latest release [1.1.0](https://github.com/TheR1D/shell_gpt/releases/tag/1.1.0) provides enhanced error details with possible solutions.
