### ISSUE TITLE
Make pipx the default installation method

### ISSUE THREAD

**Issue by grantcarthew** [TheR1D/shell_gpt#434]
I noticed very little support for [pipx](https://github.com/pypa/pipx):

https://github.com/TheR1D/shell_gpt/issues?q=is%3Aissue+pipx

I could be wrong here, I'm not an expert, but I thought pipx was becoming the default method for installing executable packages for Python.

If this statement is correct, the readme should be updated and other issues like [this one](https://github.com/TheR1D/shell_gpt/issues/323) addressed.

Thanks for your work on this project. It is fantastic.

**Comment by TheR1D** [comment]
Hi @grantcarthew, thank you for interest and suggestion. While pipx is growing in use, pip remains the standard and most widely used package manager in the Python community. Thank you again for your interest in the project.
