### ISSUE TITLE
Embedded .mov file not playing in version 1.1.0 update changelog

### ISSUE THREAD

**Issue by b9Joker108** [TheR1D/shell_gpt#435]
Hello

I just wanted to thank you and the other developers who have worked on this project. It is wonderful!

In addition, the embedded .mov file is not playing in the version 1.1.0 update changelog. I have the newest version of .mov installed and I tried to play the embedded video in two different browsers, one of them said: file corrupt. I thought that you might want to know.

Also, I just executed: ’sgpt --install-functions’ and my shell outputted:

Installing default functions...
Installed /data/data/com.termux/files/home/.config/shell_gpt/functions/execute_shell.py
Installing Linux functions...

But then noted, the documentation says that this is only specifically to execute Apple Scripts on macOS. I am running Android, could we please have this functionality for Android as well in the next version?

I tried to execute: sgpt -functions anyway to see if it would switch it on anyway, but I got the output error: No such option: -f.

Cheers
Beauford

**Comment by TheR1D** [comment]
Closing this issue due to its age and the absence of similar reports.
