### ISSUE TITLE
indentation issue in code snippet

### ISSUE THREAD

**Issue by azinsharaf** [TheR1D/shell_gpt#436]
Thanks for this great app.
when shell gpt returns a code snippet it adds blank space at the beginning of each line (see the screenshot below, highlighted in red) so if I copy it into any ide it creates indentation error. In ChatGPT copying the snippet doesn't have the issue. Am I missing something? 

![image](https://github.com/TheR1D/shell_gpt/assets/10101468/e36ea193-0d9c-4c3c-8225-cca4003e0718)

**Comment by TheR1D** [comment]
Unfortunately, the way text is rendered in a terminal/shell differs from how it's displayed in a browser. To format markdown, the shell uses space characters for indentations and formatting. When copying code snippets into an IDE, I recommend using the `--code` option to generate pure code without additional formatting.
