### ISSUE TITLE
Shell-GPT Change LLM model

### ISSUE THREAD

**Issue by karthikvijay5227** [TheR1D/shell_gpt#449]
How to solve this error

NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-1106-preview` does not exist or you do not 
have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 
'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

Even after managing to edit config file for model to be at gpt-3.5-turbo, it is showing quota exceeded but i am using new fresh api key.

RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and 
billing details. For more information on this error, read the docs: 
https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 
'code': 'insufficient_quota'}}

**Comment by cybercrimeworld** [comment]
You need to change mode version to gpt 3.5 or need to pay for this.

**Comment by karthikvijay5227** [comment]
I am already using gpt 3.5 I think.Can you give the model name
corresponding to gpt 3.5

**Comment by deltatxv** [comment]
+1, same here.

- Setting model to anything other than `gpt-3.5-turbo` (tried `gpt-3.5`, `gpt-4` and `gpt-4-0125-preview`) results in the `does not exist or you` error.
- Using `gpt-3.5-turbo` results in the `exceeded your current quota` error despite the ChatGPT web app working fine w/ 3.5 or 4 as the model.

Additional Info:
- I am paying for ChatGPT Plus.
- Tried uninstalling + reinstalling - same result.
- Tried using newly generated OpenAI keys - same result.

**Comment by TheR1D** [comment]
ChatGPT API and ChatGPT Plus subscription are billed separately. The API has its own pricing, which can be found at https://openai.com/pricing. The ChatGPT Plus subscription covers usage on chat.openai.com only. The ChatGPT API is not available for free.

**Comment by deltatxv** [comment]
Ah, thank you!

**Comment by deltatxv** [comment]
This could probably be closed as non-issue - guessing others had same issue as me (unless @karthikvijay5227 cares to object).

Or could change this issue to one of (or both):
- documentation: note that you need OpenAI API credits for this to work
- enhancement: improve error message for this case to make obvious what's wrong

**Comment by jrbecart** [comment]
As mentioned, If you have ChatGPT plus subscription you also need to buy credit here:
[https://platform.openai.com/account/billing/overview](https://platform.openai.com/account/billing/overview)

THEN wait few minutes!
