### ISSUE TITLE
Key is not pasting 

### ISSUE THREAD

**Issue by Asad-Ali-Baloch** [TheR1D/shell_gpt#450]
i have been try to past my API key in Shell-gpt but it's not pasting and i am try to write API key but i can't write it even a single letter so how can i use shell-gpt in my li
[Screencast from 2024-01-17 15-43-02.webm](https://github.com/TheR1D/shell_gpt/assets/124508836/6eeff5dc-c9cf-4b39-b681-ab8977735d9a)
nux system.
![Screenshot from 2024-01-17 15-42-29](https://github.com/TheR1D/shell_gpt/assets/124508836/dcb0b439-2bfb-4a7e-9c34-2cbc55fb6f4c)

**Comment by kyrbrbik** [comment]
You can put the key in ~/.config/shell_gpt/.sgptrc

**Comment by TheR1D** [comment]
As it was suggested, you can add your key in `~/.config/shell_gpt/.sgptrc`. Or just `export OPENAI_API_KEY="your OPENAI API key"`.
