### ISSUE TITLE
Format markdown when using custom role with chat or repl options

### ISSUE THREAD

**Issue by digitalhurricane-io** [TheR1D/shell_gpt#453]
Feature request: 

I would really like to have an option for markdown to be formatted when using the `chat` or `repl` options with custom roles. 

Ideally, the output would be formatted by default without adding an extra flag.

**Comment by TheR1D** [comment]
Implemetned in https://github.com/TheR1D/shell_gpt/pull/462. It will be released in the upcoming version.
Makrdown formatting now depends on the role description, if it contains `APPLY MARKDOWN`, ShellGPT will use markdown formatting for LLM output.
