### ISSUE TITLE
Unable to change OPENAI_BASE_URL in .sgptrc

### ISSUE THREAD

**Issue by johnd0e** [TheR1D/shell_gpt#473]
This line present in default `sgptrc`:
```
OPENAI_BASE_URL=https://api.openai.com/v1
```
I change that line, but that has no effect.
I can see that for example in error messages (`api_base = 'https://api.openai.com/v1'`).

And that is no surprise, the value in config seems unused https://github.com/search?q=repo%3ATheR1D%2Fshell_gpt%20OPENAI_BASE_URL&type=code

**Comment by TheR1D** [comment]
Hi @johnd0e, thank you for reporting this issue. I can confirm that the `OPENAI_BASE_URL` is not being used after the latest release. We will address this in upcoming updates.
