### ISSUE TITLE
Ollama/LiteLLM integration: Make api base configurable

### ISSUE THREAD

**Issue by moppman** [TheR1D/shell_gpt#474]
Hi, 

#463 enables Ollama for ShellGPT, which is awesome. 

Would you consider making the API base URL configurable in `.sgptrc`? LiteLLM defaults to `api_base="http://localhost:11434"` [here](https://docs.litellm.ai/docs/providers/ollama#example-usage).
It would be nice to be able to use ShellGPT with non-local endpoints.

Thanks!

**Comment by TheR1D** [comment]
Hi @moppman, thank you for reporting this issue. We will address this in upcoming updates. We already have an issue related to `OPENAI_BASE_URL` https://github.com/TheR1D/shell_gpt/issues/473, given that I will close this one as duplicate.
