### ISSUE TITLE
Potential Bug Report: ModuleNotFoundError for 'pkg_resources'  with pipx

### ISSUE THREAD

**Issue by hcal** [TheR1D/shell_gpt#479]
### Description
After upgrading shell-gpt using `pipx upgrade-all`, running the `sgpt` command results in a `ModuleNotFoundError` for the `pkg_resources` module. This issue has been encountered on both Fedora and Debian Linux desktops.

### Environment
- Operating System: Linux (Fedora and Debian)
- shell-gpt version: ShellGPT 1.3.0

### Steps to Reproduce
1. Install `shell-gpt` using `pipx` 
2. upgrade pipx `pipx upgrade-all`.
3. Run the `sgpt` command.

### Expected Behavior
The `sgpt` command should run without any errors.

### Actual Behavior
The following error is encountered:ModuleNotFoundError: No module named 'pkg_resources'

### Workaround
The issue was resolved by injecting `setuptools` into the `shell-gpt` environment using the following `pipx` command:
pipx inject shell-gpt setuptools
This just adds the setuptools packages to environment.

### Notes
I suspect anyone installing fresh would have the same issue.  Pipx has worked for me in the past and I've upgraded each time the same way.  If pipx isn't an expected use case feel free to close the case.

**Comment by sorokine** [comment]
this is due to imports in litellm and was fixed here: https://github.com/BerriAI/litellm/pull/1947
