### ISSUE TITLE
Importing litellm is slow

### ISSUE THREAD

**Issue by EasternJournalist** [TheR1D/shell_gpt#482]
Though litellm is convenient, it is heavy to import. As a result, every time exceuting sgpt involves a delay of 1~2 seconds even if the request is already cached. It might be a good idea to decide whether to import openai (by default, which is faster and suits most users) or litellm (when using customized models) in accordance to the configuration.

**Comment by TheR1D** [comment]
Released in [1.4.0](https://github.com/TheR1D/shell_gpt/releases/tag/1.4.0).
