### ISSUE TITLE
Error: ShellGPT integrations only available for ZSH and Bash. 

### ISSUE THREAD

**Issue by soullessschizo** [TheR1D/shell_gpt#492]
i am running zsh but getting that error.

$SHELL --version
zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

echo $SHELL                    
/usr/bin/zsh

**Comment by CrashBandicooch** [comment]
> issue was that my zsh is at /usr/bin/zsh, and shell-gpt only checks in /bin/zsh
> 
> i fixed it by editing line 76 of .local/lib/python3.10/site-packages/sgpt/utils.py to: if shell == "/usr/bin/zsh":

I had the same issue and this worked for me. Just make sure you're looking in the right location for the file. I had installed sgpt with `pipx`, so the path to `utils.py` was different for me.
