### ISSUE TITLE
change api key

### ISSUE THREAD

**Issue by kisslessvirgin** [TheR1D/shell_gpt#5]
How do I change the API key? I accidentally entered it wrong and I can't seem to even reset it.
I've tried:
deleting sgpt.py in ~/.local/lib/python3.11/site-packages and /usr/local/bin
I know there's supposed to be a text file somewhere but I cant find it.
Any help appreciated!

**Comment by TheR1D** [comment]
Hi, install it again:
```shell
pip install shell-gpt --user
```
Then you would need to delete your API key txt file:
```shell
rm ~/.config/shell-gpt/api_key.txt
```
And try to run sgpt again:
```
sgpt "test"
```
It will ask your API key.

**Comment by kid-gorgeous** [comment]
Ran into this problem last week during installation, solved it right away!

**Comment by wfc0909** [comment]
This thread solved the same case and I am finding this ai tool may help a lot in coding. Thank you.

**Comment by xsoc** [comment]
Looks like the file has changed now, I found my key in
`~/.config/shell_gpt/.sgptrc`
Just `nano` it, and update the `OPENAI_API_KEY=` as appropriate

**Comment by woejefe** [comment]
what is the command on windows... where is the directory. does it go into python or pip folder?

**Comment by xsoc** [comment]
On windows try `notepad %USERPROFILE%\.config\shell_gpt\.sgptrc`

**Comment by m4l490n** [comment]
I'm having this issue too but there is no `~/.config/shell-gpt/api_key.txt` and I can't seem to be able to completely purge sgpt in order to install it again.
