### ISSUE TITLE
Want to add the ability to translate local files directly

### ISSUE THREAD

**Issue by shawokou123** [TheR1D/shell_gpt#510]
Want to add the ability to translate local files directly !

For example, there is a file english.txt locally, and I hope that the contents of this file can be translated directly through sgpt.

**Comment by MokaCubrew** [comment]
Is thie method not enough?
```shell
cat english.txt | sgpt "Translated into spanish. Results only." > spanish.txt
```

**Comment by shawokou123** [comment]
OK, thank you very much!!!
Is there a good translation prompt  ?

**Comment by shawokou123** [comment]
OK, thank you very much!!!
Is there a good translation prompt ?
such as:

sgpt "Hello chatgpt, you were created to do all kinds of translation work.Please help to do the designated language translation work, mainly English or other languages, complete and correct translation into Chinese.If you need to store any data, assume it will be stored in the conversation.APPLY MARKDOWN formatting when possible.If there are English names in the article, keep their original names and do not translate them. For example, 'elon musk' does not need to be translated! Keep 'elon musk'. Results only！"

**Comment by TheR1D** [comment]
I think the suggestion provided by @MokaCubrew is sufficient in this case, given that closing this issue.
