### ISSUE TITLE
Is it possible to support gemini api

### ISSUE THREAD

**Issue by 4t8dd** [TheR1D/shell_gpt#514]
I am not sure how big the difference between gpt and gemini. I assume it is small based on some open report.
I wonder if it is possible to support gemini api? It is free anyway.

**Comment by CheerfulPianissimo** [comment]
https://github.com/zhu327/gemini-openai-proxy seems like it could be used for this.

**Comment by CheerfulPianissimo** [comment]
Ok, can confirm that works. Just set API_BASE_URL to http://localhost:8080/v1 and the openai key to your gemini api key.

**Comment by 4t8dd** [comment]
@CheerfulPianissimo Thanks for your trying. It works for too. 
And there is another [repo](https://github.com/PublicAffairs/openai-gemini/tree/main?tab=readme-ov-file) with which you can deploy this proxy to some saas and it works perfectly for me .

**Comment by nullnuller** [comment]
Is anyone else having this issue?
```$ curl http://127.0.0.1:8081/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer $API_KEY" -d '{
"model": "gpt-4",
"messages": [{"role": "user", "content": "Say this is a test!"}],
"temperature": 0.7
}'
curl: (52) Empty reply from server

Here's the docker:
$ docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
9a49c5c0b3e4 zhu327/gemini-openai-proxy:latest "/app/gemini" 3 minutes ago Up 3 minutes 0.0.0.0:8081->8081/tcp gemini
```
