### ISSUE TITLE
ShellGPT Running Linux Commands in Windows

### ISSUE THREAD

**Issue by CyrixJD115** [TheR1D/shell_gpt#537]
I use ShellGPT directly on windows, since Ollama is now available for Windows without WSL2.
I Installed Ollama on Windows 11 Pro and config the file to disable OpenAI API args and use local models which is litellm for using local models.

Now while it was able to run great for general knowledge, chatting and learn commands (to the extent), but the main issue is that Im aware that ShellGPT is designed for Linux while using local models, I could use OpenAI but I dent want to pay for it.

However when I use the "--shell" to ask and execute for me, it did generate a command but it wont execute correctly since I noticed it was mainly designed for Linux if Im not mistaken, heres an example it tried running on Normal Windows PowerShell  

```
PS C:\Users\CyrixJD115> sgpt --shell "create a text file in the root of C:\ drive, and append the text file 'Hello world' and named the text file 'sgpt_test'"
$Content = "Hello world"
New-Item -Path "C:\sgpt\_test.txt" -ItemType File -Force || Set-Content -Path "C:\sgpt\_test.txt" -Value $Content -Force
[E]xecute, [D]escribe, [A]bort: E
Hello : The term 'Hello' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:12
+ $Content = Hello world
+            ~~~~~
    + CategoryInfo          : ObjectNotFound: (Hello:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\CyrixJD115> sgpt --shell "create a text file in the root of C:\ drive, and append the text file 'This_is_power' and named the text file 'sgpt_test'"
$Content = "This_is_power"
# or in one command
New-Item -Path "C:\sgpt_test.txt" -ItemType File -Force -ErrorAction SilentlyContinue; Set-Content -Path "C:\sgpt_test.txt" -Value "This_is_power" -Force
[E]xecute, [D]escribe, [A]bort: D
Creates a new file named "C:\sgpt_test.txt" with the content "This_is_power", using New-Item to create the file if it doesn't exist and Set-Content to write the content, both with force creation and error
silence.

 • New-Item: Creates a new item in the file system.
    • -Path "C:\sgpt_test.txt": Specifies the path of the new item.
    • -ItemType File: Sets the type of the new item as a file.
    • -Force: Forces creation of the item even if it already exists.
    • -ErrorAction SilentlyContinue: Continues execution silently if an error occurs.
 • Set-Content: Sets the content of an existing file.
    • -Path "C:\sgpt_test.txt": Specifies the path of the file to update.
    • -Value $Content: Sets the new content of the file, which is a PowerShell variable in this case.
    • -Force: Forces writing to the file even if it's read-only or doesn't exist.
[E]xecute, [D]escribe, [A]bort: E
This_is_power : The term 'This_is_power' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:12
+ $Content = This_is_power
+            ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (This_is_power:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
((Or look at the Image))
![image_2024-04-07_174654444](https://github.com/TheR1D/shell_gpt/assets/129636984/1c3c064f-b47c-4cc4-aab7-5ea14ed8b9fa)

While this is an issue for windows version of Ollama when ShellGPT is not "generating" correctly for windows, when its doing in Linux when Ollama was only designed for MacOS or Linux, but now its availble for Windows. Look below for proof its availble for windows

https://ollama.com/download/windows
![image_2024-04-07_175020267](https://github.com/TheR1D/shell_gpt/assets/129636984/26c5d5f8-d45f-4afe-aa3c-6c8d7135c998)

It would be awesome if this issue can be resolved, or Im doing something wrong let me know, thank you

**Comment by Robinsane** [comment]
Could you try
`sgpt --chat "What is your purpose?"`
When sgpt explains his purpose he tells you what operating system and shell his system prompt is configured for.

I had a problem where it detected the os and shell wrongly, because I run it in a container.
Fixed it for me in following PR: #540
