### ISSUE TITLE
Feature request: Conversation loop mode

### ISSUE THREAD

**Issue by buzzert** [TheR1D/shell_gpt#54]
I think it would be really cool if there was an option to start `sgpt` with a loop/readline mode that continuously accepted input and automatically generated a chat identifier. 

For example, you should be able to invoke something like `sgpt --chat-continuous`, which would then print some kind of prompt character (e.g., ">"), and the user can interact with ChatGPT just by typing and hitting enter, rather than having to format the entire input as a command line argument.

**Comment by TheR1D** [comment]
It can be implemented in coming patches. Using CLI options for `--chat` is not the best, all chat functionality should be moved to dedicated subcommand, something like:
```
sgpt chat [id]  # Loop mode
sgpt chat [id] --no-chat  # Normal mode.
sgpt chat [id] --show  # Show all message related on session.
sgpt chat --list  # Show sessions.
```
