### ISSUE TITLE
Feature request: add support for Perplexity API

### ISSUE THREAD

**Issue by wajdi-b** [TheR1D/shell_gpt#558]
Perplexity supports many LLM out of the box and has an [API](https://docs.perplexity.ai/) similar to OpenAI. People who already have it would benefit from using their subscription instead of getting charged by OpenAI on top.

**Comment by jeanlucthumm** [comment]
You can use LiteLLM already. Doesn't that do the same thing?

**Comment by wajdi-b** [comment]
It actually works great without it by just setting configuration variables `API_BASE_URL` to `https://api.perplexity.ai`, `OPENAI_API_KEY` to the Perplexity API key, as well as `DEFAULT_MODEL` to one of the values found [here](https://docs.perplexity.ai/docs/model-cards)
