### ISSUE TITLE
[Feature request] support chat in docker container mode

### ISSUE THREAD

**Issue by binaryoak** [TheR1D/shell_gpt#56]
since currently the container is not running in the detach mode,  it won't be able to store any chats in local, ```--chat ``` ```--list-chat``` ```--show-chat``` are basically not usable with the container

**Comment by TheR1D** [comment]
@eric-glb Would you like to implement it?

**Comment by eric-glb** [comment]
I can try ^^

**Comment by eric-glb** [comment]
#59 is addressing this feature request.  
BTW it may be interesting to have a sgpt `--delete-chats` option to purge the cached chats.
