### ISSUE TITLE
[Feature Request] Add ability to continue conversation base on previously ran commands

### ISSUE THREAD

**Issue by Pablo1107** [TheR1D/shell_gpt#6]
One big feature of ChatGPT is it can use relevant information based on previous prompts and responses, for example:

```
~
❯ sgpt --code "make an example request to localhost:3000 using python"
import requests

response = requests.get('http://localhost:3000')
print(response.text)

~
❯ sgpt --code "now that but with cache"
// Setting a cache
let cache = {};

// Function to be cached
function add(a,b){
    if (!cache[`${a},${b}`]) {
        cache[`${a},${b}`] = a + b;
    }
    return cache[`${a},${b}`];
}
```

Something like that should return the same code as before but probably using `requests_cache`. The best approach probably will be to add a new argument to `--follow-conversation` or something like that.

Thoughts?

**Comment by TheR1D** [comment]
Unfortunately this is not possible now with current model used by sgpt, it doesn't use ChatGPT (OpenAI didn't publish their api for it yet) it uses other model from GPT-3 family which is `text-davinci-003` and this particular model doesn't save previous promtps context. When OpenAI will release their public API for ChatGPT (probably soon), it will be possible to implement suggested feature.

**Comment by Pablo1107** [comment]
> Unfortunately this is not possible now with current model used by sgpt, it doesn't use ChatGPT (OpenAI didn't publish their api for it yet) it uses other model from GPT-3 family which is `text-davinci-003` and this particular model doesn't save previous promtps context. When OpenAI will release their public API for ChatGPT (probably soon), it will be possible to implement suggested feature.

Oh, I was worried this was the case. Hopefully OpenAI will release it soon. 🤞

**Comment by Pablo1107** [comment]
@TheR1D seems like a similar result can be done using `text-davinci-003` with [template prompts](https://www.youtube.com/watch?v=RflBcK0oDH0). In this case will be saving previous prompts and answers and make a prompt template with something like this:

```
The following are extract from conversations with an AI
assistant.

User: Write the number 30.
AI: 30

User: What is that number plus 10?
AI:
```

And hopefully the model will return 40. I didn't try it myself but if ChatGPT API does not go public or it takes time this might be a good try.

**Comment by TheR1D** [comment]
For simple cases it works, but I'm not sure how it will perform for long conversations or long prompts. For now I think it is possible to achive it with additional shell magic, for example: 
```shell
# Make a query and save output to file.
sgpt --code "make an example request to localhost:3000 using python" > request.py
# Ask for caching and provide previous code from file.
sgpt --code "now that but with cache \n $(cat request.py)"
```

**Comment by Pablo1107** [comment]
Has this change with the 0.6 release?

**Comment by TheR1D** [comment]
No, it is not implemented yet.
