### ISSUE TITLE
sgpt command doesn't work on macos and misc comments

### ISSUE THREAD

**Issue by ecsplendid** [TheR1D/shell_gpt#66]
It installed OK but couldn't run with the sgpt command, I had to add a function into my zprofile

```
sgpt() {
    python3 /Users/[...]/Library/Python/[version]/lib/python/site-packages/sgpt/app.py "$@"
}
```

I think the most important and exciting feature (on your roadmap) is the **interactive** chat mode, where you can ask questions, it will execute commands, and the responses of those commands become part of the context, so you can then refine and refine i.e. 

* What are the files in this directory
* Sort them by name
* Concatenate them using FFMPEG
* Convert the resulting file into an MP3
* ...

I didn't check if you already do this, assume you do, but it's very important that the **outputs** from the shell command become part of the context too. 

Also we need some prompt engineering:

```
sgpt --chat number "whats in this directory"
I'm sorry, I cannot answer this question as you have not provided me with the name or path of the directory.
```

You see, it doesn't even know that we expect it to give us shell commands, and it doesn't even have the basic context of which directory I am in

Also often ChatGPT responds with hedging text like "as a language model I can't do XYZ, but here you go anyway.." we should prompt it to not say that, as it's super annoying

Great work though, looking very promising :)

**Comment by go-dockly** [comment]
try like so
➜  ~ python3 -m sgpt

**Comment by TheR1D** [comment]
@ecsplendid 
Thank you for such detailed feedback. 
Make sure you have `site-packages` in your `$PATH`:
```
pip show shell-gpt
...
# In my case it is located in homebrew dir where my Python lives.
Location: /opt/homebrew/lib/python3.10/site-packages  # Should be in $PATH
```
You can add context to your prompt using `--shell` option (it will add "provide only shell command as output" to the prompt), and it works as you are expecting:
```
sgpt --shell --chat c1 "whats in this directory"
# -> ls
```
