### ISSUE TITLE
choose model by argument

### ISSUE THREAD

**Issue by go-dockly** [TheR1D/shell_gpt#67]
It would be useful to have a -m (--model 'gpt-4') argument for sgpt

https://platform.openai.com/docs/models/gpt-4

**Comment by TheR1D** [comment]
Currently GPT-4 is not available thru API, when OpenAI will allow to use it via API, it will be implemented.

**Comment by go-dockly** [comment]
is there a possibility to specify a model by cmd arg?
could this be added?

**Comment by TheR1D** [comment]
Currently `sgpt` uses `/chat` API endpoint, which has only two available model options (except coming GPT-4): `gpt-3.5-turbo` - used by `sgpt` and `gpt-3.5-turbo-0301`. I think there is no reason to use `gpt-3.5-turbo-0301` with `sgpt`. Imho it doens't make sense to have `--model` option for now, but once GPT-4 will be available over API, it will be implemented.

**Comment by go-dockly** [comment]
coming gpt 4 it has this option gpt-4-32k (Same capabilities as the base gpt-4 mode but with 4x the context length)
so eventually it would be nice to differentiate between those but you are absolutely right it doesn't make sense to differentiate between -0301 versions.

**Comment by mdonaberger** [comment]
Just commenting to say that I got into the GPT-4 on API preview — I can imagine that it's rolling out now to a lot of people soon.

**Comment by lpurdy01** [comment]
I have just realized this does have the follow on issue of chats don't keep track of what model they were conducted with. I will have to see how this interacts.

**Comment by lpurdy01** [comment]
Nvm. It seems to work fine switching models with the same chat_id
