### ISSUE TITLE
Where to put the generated API key?

### ISSUE THREAD

**Issue by PrabuddhMathur** [TheR1D/shell_gpt#7]
I generated the OpenAI API key from their website, now where do i keep it for it to work. Also, just by pip install shell-gpt it does not work at all as a command. Please help!

**Comment by aunicorn111** [comment]
How did you resolve the issue??

**Comment by TheR1D** [comment]
@aunicorn111 Checkout our [wiki](https://github.com/TheR1D/shell_gpt/wiki#changing-api-key)
