### ISSUE TITLE
Reset chat

### ISSUE THREAD

**Issue by edshamis** [TheR1D/shell_gpt#74]
Sorry if I missed it in the readme, but how to start over a chat (same --chat id)?

**Comment by TheR1D** [comment]
It is not mentioned in the README; I will add it there. You can list your chat sessions using the sgpt --list-chat command, which will display all your chat sessions (just files in the temp directory):
```
.../some_session
.../another_session
```
To reset a specific chat session, simply delete the corresponding file:
```
rm /tmp/.../some_session
sgpt --chat some_session "prompt..."
```

**Comment by haim0n** [comment]
hey, I added a PR to address this: #129

**Comment by TheR1D** [comment]
I think user can manage deletion of chats just by deleting the "chat" file which is provided by `sgpt --list-chats`
