### ISSUE TITLE
Too Many Requests for url error

### ISSUE THREAD

**Issue by Pranjal-Patel** [TheR1D/shell_gpt#75]
When i'm using the cli, its giving me this error
```
HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/chat/completions
```

**Comment by remainisyours** [comment]
It seems you are using free version of ChatGPT which restricts frequency of API hits.

As per free-tier plan, one can have a **20-request limit per minute**, with **150,000 tokens** per minute. While paid users contain a rate limit of 60 RPM and 250 TPM in their first 48 hours. After 48 hours the rate limits of paid users turn to 3,500 RPM and 350,000 TPM. 

Hope this answers the issue.

**Comment by digitalmouse** [comment]
That makes sense, but I have not used ChatGPT in over 2 months, so my free tier account should be 'fresh' with the unused 20-request limit per minute.

After installing ShellGPT and trying an example, I get the 429 error immediately. I've tried 4 example requests in the past 10 minutes, all with the same error.    

So I do not believe at this point it is a limit-per-minute issue.

**Comment by BSD-Yassin** [comment]
> 

Just a shot in the dark, but have you tried refreshing the API token to a new one ? Just in case that one was tied to the free tier ?

**Comment by digitalmouse** [comment]
Solved it (for me at least).  After making sure I had 'credit' to make requests, I closed down all my open terminals, open a new terminal session, walked through the tutorial (again) at https://beebom.com/how-use-chatgpt-linux-terminal/ (probably over kill), and now it works.  So lesson is to make sure you have request credit available and not expired.  :)

**Comment by AnkitGupta17134** [comment]
I don't think so there is limit like $18 credits to a free tier account. Can you point to official references for same? Thanks

**Comment by Naren-Hub** [comment]
> I don't think so there is limit like $18 credits to a free tier account. Can you point to official references for same? Thanks

i was getting this error too. I am not able to find $18 credit though. However i can see my accounts usage here: https://platform.openai.com/account/usage

**Comment by TheR1D** [comment]
We have some information regarding to this ussue on our [wiki page](https://github.com/TheR1D/shell_gpt/wiki#httperrors).

**Comment by Xtron135** [comment]
So the conclusion is if the trial credit provided is finished, we need to use the paid version of ChatGPT to be able to use ShellGPT?

**Comment by eventhorizon02** [comment]
I am able to chat via the web page but through the shell I am also getting the "too many request for url" error
Do I have to be a paid member to use sgpt?

**Comment by TheR1D** [comment]
No, you don't need a paid membership to use `sgpt`. If you haven't exceeded your [limit](https://platform.openai.com/account/usage) and you're receiving a `429: too many requests for URL` error, this typically means OpenAI is experiencing high traffic and server overloads, just retry your requests after a brief wait.

**Comment by eventhorizon02** [comment]
I have tried 6 or 7 times over a period of two days and got the same 429 error every time. As a matter of fact I was not able to get a reply even once, yet accessing it through the browser works. So I'm thinking there is some other problem.

**Comment by Xtron135** [comment]
> No, you don't need a paid membership to use `sgpt`. If you haven't exceeded your [limit](https://platform.openai.com/account/usage) and you're receiving a `429: too many requests for URL` error, this typically means OpenAI is experiencing high traffic and server overloads, just retry your requests after a brief wait.

If we reached the limit, how to apply for more 'limit'? Ive go through the billing page. So do we need to pay if we have reached our limit? If no, how to increase the limit back without paying?.

**Comment by rarahim75** [comment]
You don't need to have a paid account to use sgpt provided the free trial credit given is still valid and has not been used up. Otherwise, you have to be a paid member. I had the same issue. Requests made through sgpt were returning 429, since my free trial credit has expired. Once i converted to a paid account (charged on per use basis), my requests were coming through successfully.

**Comment by CharlotteCross1998** [comment]
I'm having the same issue. Newly generated token, have $17.87 credit remaining and I can chat on chat.openai.com/chat perfectly fine, so I would assume the servers aren't down.

**Comment by CharleeWa** [comment]
ChatGPT Web service and OpenAI Account (API) are two different services. Just because ChatGPT can reply to content doesn't mean the API can. You need to check the API usage.

**Comment by Pablo1107** [comment]
![image](https://user-images.githubusercontent.com/17091659/230742245-a2b7a8c1-60a4-4581-84e2-354ece47ad7f.png)
Probably most people encountering this issue are being mislead by the "remanining" credit. They give you 3 months of free tier, but after that it's expired, as you can see my free credit expired April 1st 2023 (kindof a joke). It is what it is.
