### ISSUE TITLE
After adding OPEN_AI key, throws PROMT not added

### ISSUE THREAD

**Issue by AnkitGupta17134** [TheR1D/shell_gpt#76]
Hi 

During a fresh installation of shell-gpt, at first asks for `API_KEY`. 
It reads and stores the key successfully but throws `PROMT not specified` as well.

Ideally it should store the API key with a prompt like `Key has been added` and shouldn't trigger/check for PROMT out there. 
Let me know your thoughts.

Also Kudos to aesthetic UI in terminal too :tada:

**Comment by TheR1D** [comment]
Thank you for reporting this issue. Validation for empty `PROMPT` has been removed in  https://github.com/TheR1D/shell_gpt/pull/455. Now ShellGPT will show a message from LLM, something like
> Hello! How can I assist you today? ...
