### ISSUE TITLE
Timestamp Conversion example in readme is wrong

### ISSUE THREAD

**Issue by leumasme** [TheR1D/shell_gpt#77]
This kind of thing will never stop happening and it will never stop being funny. Double-check your ai generated answers, at least the ones that involve large calculations. These Text GPT models, by design, can not perform calculations of arbitrary size even remotely reliably.

With that said, here's a quote from the readme:
> sgpt "$(date) to Unix timestamp"
> \# -> The Unix timestamp for Thu Mar 2 00:13:11 CET 2023 is 1677327191.

This is wrong. The generated timestamp is actually for some time on Feb 25 2023.
I believe this example should not be corrected and instead removed or used as an example of unreliability, as the model is not capable of reliably doing calculations like this as stated above.

**Comment by TheR1D** [comment]
You are right, the timestamp was wrong, readme was updated. Thanks for reporting this.
