### ISSUE TITLE
A --continue option, so we don't need to invent and retype chat ids

### ISSUE THREAD

**Issue by joeytwiddle** [TheR1D/shell_gpt#78]
### Problem

I don't always know when I want to ask ChatGPT a follow-up question. I only know _after_ it has given a response. And I don't want to keep inventing session names (chat ids), just in case I need them. Also, passing chat ids is a lot of typing.

### Possible solution

I suggest a `--continue / -c` option which allows us to continue from the last query we made.

Here is an example:

```sh
$ sgpt 'Ask a question?'
[response]
# I am happy with the answer, and happy for the chat session to end.

$ sgpt 'Ask a different question?'
[response]
# I am not satisfied. I want to continue the discussion with a followup query. So I use -c.
$ sgpt -c 'Ask followup to the previous question?'
[response]
$ sgpt -c 'Ask another followup in the same session?'
[response]
```

Advantage: No session names, and less typing.

### Possible implementation

- Every basic query should start a new chat session, with a randomly generated id.
- `sgpt` could store the id of the latest session somewhere.
- If `--continue` is passed, then instead of starting a new chat session, `sgpt` should continue the latest stored session.

**Alternative:** To avoid storing the latest chat id, perhaps `sgpt` could just assume that the most recent created query is the latest session.

**Alternative:** It might make sense to use `--followup / -f` or `--reply / -r` instead, to keep `-c` as a shortcut for `--chat`

Does this sound like a good idea? Or is there already a good way to do this in `sgpt`?

**Comment by joeytwiddle** [comment]
I tried to implement this, but there is a runtime error: `got an unexpected keyword argument 'followup'`

Could someone who understand Python take a look? What have I missed?

https://github.com/TheR1D/shell_gpt/compare/main...joeytwiddle:shell_gpt:add-followup-broken?expand=1

**Comment by TheR1D** [comment]
`sgpt --chat temp` can be used for quick chat sessions, implemented in https://github.com/TheR1D/shell_gpt/pull/94. For followup we can use REPL mode, which makes it easy to tweak AI suggestions.
