### ISSUE TITLE
[Feature request] Handle linebreaks

### ISSUE THREAD

**Issue by annawoodard** [TheR1D/shell_gpt#8]
Thank you for this fantastic tool! 🙏 🙏 🙏 

Your tool is a game-changer for me, especially since I can't access ChatGPT while I have my VPN enabled, so I can't use it at all while working.

It would be nice to have a natural way to handle linebreaks-- for example, for a prompt like "convert the following code from Pytorch to Tensorflow." Perhaps sgpt could drop you into `$EDITOR` the same way git does, where you could paste your text, and then exit.

Thoughts?

**Comment by TheR1D** [comment]
Thank you for your feedback!

The feature you are suggesting is actually a good idea. It can be implemented using additional argument for example, you would call `sgpt --editor` and it will drop you into `$EDITOR` where you could write entire prompt including code:
```
convert the following code from Pytorch to Tensorflow:
import torch
...
```

**Comment by TheR1D** [comment]
Implemented with `--editor` argument in PR https://github.com/TheR1D/shell_gpt/pull/27
