### ISSUE TITLE
Accept stdin input

### ISSUE THREAD

**Issue by Shakahs** [TheR1D/shell_gpt#80]
It would be very useful to pipe stdin to sgpt, then ask a question about said input. For example:

cat data.json | sgpt "what is the oldest entry"
cat script.py | sgpt "what does this script do?"

etc.

**Comment by TheR1D** [comment]
But you can do the same thing with command substitution syntax, as it is described in readme:
```
sgpt "what is the oldest entry: $(cat data.json)"
```

**Comment by Shakahs** [comment]
Perhaps, but it is not practical. Pipelining commands is a basic tenet of CLI usage and shell scripting. For SGPT to be the shell's interface to GPT it must support the IO capabilities expected of a shell utility. This is the third issue on the subject (see #35, #86) so clearly it is needed. I have created a pull request implementing it in #93.
