### ISSUE TITLE
sgpt -se failed with "sh: 1: Command:: not found"

### ISSUE THREAD

**Issue by stingshen** [TheR1D/shell_gpt#99]
For example:

![image](https://user-images.githubusercontent.com/6214067/227720828-5de56ebd-0195-4333-866c-5bf4d30e645b.png)

I guess the root cause is chat gpt outputs extra `Command: ` prefix.

**Comment by joeytwiddle** [comment]
ChatGPT is not always obedient!

https://github.com/TheR1D/shell_gpt/blob/caa4fbfb8e8d9bc50ef337510f33eb6eb94238eb/sgpt/make_prompt.py#L25-L35

You may retry with `--no-cache`

**Comment by stingshen** [comment]
> ChatGPT is not always obedient! It was asked not to do this:
> 
> https://github.com/TheR1D/shell_gpt/blob/caa4fbfb8e8d9bc50ef337510f33eb6eb94238eb/sgpt/make_prompt.py#L25-L35
> 
> You may retry with `--no-cache`

Thank you
